import { before, after, test } from 'node:test';
import assert from 'node:assert/strict';
import { startHarness, observeBrowser, eventually } from './browser-harness.mjs';

let harness;
before(async()=>{harness=await startHarness();},{timeout:60000});
after(async()=>{await harness?.close();},{timeout:15000});
async function fixture(t,options={}){const context=await harness.browser.newContext(options.viewport?{viewport:options.viewport}:undefined);t.after(()=>context.close());await context.addInitScript(observeBrowser);const page=await context.newPage();if(options.reducedMotion)await page.emulateMedia({reducedMotion:options.reducedMotion});page.setDefaultTimeout(8000);await page.goto(harness.origin+'/laboratorio-cimatico?frequency=432&waveform=sine&binaural=8');return page;}

test('cymatics route: generator parameters, independent binaural views and shared existing audio graph', {timeout:45000}, async t=>{
  const page=await fixture(t);assert.equal(await page.getByRole('spinbutton',{name:'Frecuencia cimática'}).inputValue(),'432');assert.equal(await page.getByRole('img',{name:'Canal izquierdo'}).count(),1);assert.equal(await page.getByRole('img',{name:'Canal derecho'}).count(),1);assert.match(await page.getByText(/Diferencia:/).first().innerText(),/8.0 Hz; no es un tono emitido/);
  await page.getByRole('button',{name:'Escuchar tono'}).click();let probe=await page.evaluate(()=>window.__fhUI.snapshot());assert.deepEqual(probe.contexts.flatMap(c=>c.oscillators.map(o=>o.frequencies[0])).slice(-2),[432,440]);await page.getByRole('button',{name:'Detener sonido'}).click();await eventually(async()=>{probe=await page.evaluate(()=>window.__fhUI.snapshot());assert.ok(probe.contexts[0].oscillators.every(o=>o.ended&&o.disconnected));});
});

test('cymatics route: surface switch, A/B, explicit gallery save and reload', {timeout:45000}, async t=>{
  const page=await fixture(t);await page.getByRole('combobox',{name:'Superficie'}).selectOption('circular-membrane');await page.getByRole('button',{name:'Guardar A'}).click();await page.getByRole('spinbutton',{name:'Frecuencia cimática'}).fill('528');await page.getByRole('button',{name:'Guardar B'}).click();await page.getByRole('button',{name:'Comparar'}).click();assert.equal(await page.getByRole('img',{name:'Comparación A'}).count(),1);assert.equal(await page.getByRole('img',{name:'Comparación B'}).count(),1);assert.match(await page.getByText(/escala visual común/).innerText(),/Superficie física idéntica/);
  await page.getByRole('button',{name:'Guardar figura'}).click();await page.getByRole('heading',{name:'Galería local (1)'}).waitFor();const storage=await page.evaluate(()=>({...localStorage}));assert.equal(Object.keys(storage).length,1);assert.ok(storage['fh:cymatics-gallery-v1']);await page.reload();await page.getByRole('heading',{name:'Galería local (1)'}).waitFor();assert.equal((await page.evaluate(()=>window.__fhUI.snapshot())).contexts.length,0);
});

test('cymatics resonance demo exposes three computed patterns, does not autoplay and preserves binaural separation', {timeout:45000}, async t=>{
  const page=await fixture(t),selector=page.locator('select[aria-label="Ejemplo de resonancia"]');await selector.waitFor();assert.equal(await selector.locator('option').count(),3);const volume=await page.getByText(/Volumen de escucha/).locator('input').inputValue();
  await selector.selectOption('plate-2-2');await page.getByRole('button',{name:'Ver figura de resonancia'}).click();assert.equal((await page.evaluate(()=>window.__fhUI.snapshot())).contexts.length,0);assert.equal(await page.getByText(/Volumen de escucha/).locator('input').inputValue(),volume);assert.match(await page.getByRole('status').filter({hasText:/Cuatro regiones interiores/}).innerText(),/Placa \(2, 2\)/);
  if(process.env.FH_CAPTURE_CYMATICS){await page.getByRole('combobox',{name:'Vista'}).selectOption('field');await page.getByRole('img',{name:'Canal izquierdo'}).screenshot({path:process.env.FH_CAPTURE_CYMATICS+'/cymatics-field.png'});await page.getByRole('combobox',{name:'Vista'}).selectOption('particles');await new Promise(resolve=>setTimeout(resolve,4500));await page.getByRole('img',{name:'Canal izquierdo'}).screenshot({path:process.env.FH_CAPTURE_CYMATICS+'/cymatics-particles.png'});}
  await page.getByRole('combobox',{name:'Vista'}).selectOption('nodal-lines');assert.equal(await page.getByRole('img',{name:'Canal izquierdo'}).count(),1);
  await selector.selectOption('membrane-0-2-cos');await page.getByRole('button',{name:'Ver figura de resonancia'}).click();assert.match(await page.getByRole('status').filter({hasText:/Anillo concéntrico/}).innerText(),/Membrana \(0, 2\)/);
  await selector.selectOption('membrane-3-1-cos');await page.getByRole('button',{name:'Ver figura de resonancia'}).click();assert.match(await page.getByRole('status').filter({hasText:/Seis sectores/}).innerText(),/Membrana \(3, 1\)/);
  await page.getByRole('button',{name:'Escuchar tono'}).click();const probe=await page.evaluate(()=>window.__fhUI.snapshot());assert.equal(probe.contexts.length,1);assert.equal(probe.contexts[0].oscillators.length,3);assert.notEqual(probe.contexts[0].oscillators.at(-2).frequencies[0],probe.contexts[0].oscillators.at(-1).frequencies[0]);await page.getByRole('button',{name:'Detener sonido'}).click();
});

test('cymatics live frequency control redraws the computed surface and follows existing audio without autoplay', {timeout:45000}, async t=>{
  const page=await fixture(t),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.locator('select[aria-label="Ejemplo de resonancia"]').selectOption('plate-2-2');await page.getByRole('button',{name:'Ver figura de resonancia'}).click();await page.getByRole('combobox',{name:'Vista'}).selectOption('vibration');const canvas=page.getByRole('img',{name:'Canal izquierdo'}),box=await canvas.boundingBox();assert.ok(box&&box.width<=881&&Math.abs(box.width/box.height-4/3)<.03);const before=await canvas.evaluate(node=>node.toDataURL());await page.waitForTimeout(250);const animated=await canvas.evaluate(node=>node.toDataURL());assert.notEqual(animated,before);const fine=page.getByRole('slider',{name:'Exploración fina de frecuencia'}),minimum=Number(await fine.getAttribute('min')),setFine=value=>fine.evaluate((node,next)=>{node.value=String(next);node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));},value),next=minimum+5;await setFine(next);await page.waitForTimeout(100);const after=await canvas.evaluate(node=>node.toDataURL());assert.notEqual(after,animated);assert.equal((await page.evaluate(()=>window.__fhUI.snapshot())).contexts.length,0);assert.match(await page.getByText(/Frecuencia actual:/).innerText(),new RegExp(next.toFixed(2).replace('.','\\.')));
  await page.getByRole('button',{name:'Escuchar tono'}).click();await page.getByRole('button',{name:'Detener sonido'}).waitFor();const nextAudio=minimum+10;await setFine(nextAudio);const probe=await page.evaluate(()=>window.__fhUI.snapshot()),left=probe.contexts[0].oscillators.at(-2).frequencies;assert.ok(Math.abs(left.at(-1)-nextAudio)<.1);await page.getByRole('button',{name:'Detener sonido'}).click();assert.deepEqual(errors,[]);
});

test('cymatics mobile reduced-motion repaints immediately without hide/show workaround', {timeout:45000}, async t=>{
  const page=await fixture(t,{viewport:{width:390,height:844},reducedMotion:'reduce'});await page.locator('select[aria-label="Ejemplo de resonancia"]').selectOption('plate-2-2');await page.getByRole('button',{name:'Ver figura de resonancia'}).click();await page.getByRole('combobox',{name:'Vista'}).selectOption('vibration');const canvas=page.getByRole('img',{name:'Canal izquierdo'}),before=await canvas.evaluate(node=>node.toDataURL()),fine=page.getByRole('slider',{name:'Exploración fina de frecuencia'}),minimum=Number(await fine.getAttribute('min')),next=minimum+12;await fine.evaluate((node,value)=>{node.value=String(value);node.dispatchEvent(new Event('input',{bubbles:true}));},next);await page.getByText(/Frecuencia actual:/).filter({hasText:next.toFixed(2)}).waitFor();const after=await canvas.evaluate(node=>node.toDataURL());assert.notEqual(after,before);assert.equal(await page.getByRole('button',{name:'Mostrar visual'}).count(),0);
});

test('cymatics particles reset and reveal the newly calculated field when frequency changes', {timeout:45000}, async t=>{
  const page=await fixture(t,{reducedMotion:'reduce'});await page.locator('select[aria-label="Ejemplo de resonancia"]').selectOption('plate-2-2');await page.getByRole('button',{name:'Ver figura de resonancia'}).click();await page.getByRole('combobox',{name:'Vista'}).selectOption('particles');const canvas=page.getByRole('img',{name:'Canal izquierdo'}),before=await canvas.evaluate(node=>node.toDataURL()),fine=page.getByRole('slider',{name:'Exploración fina de frecuencia'}),minimum=Number(await fine.getAttribute('min')),next=minimum+12;await fine.evaluate((node,value)=>{node.value=String(value);node.dispatchEvent(new Event('input',{bubbles:true}));},next);await page.getByText(/Frecuencia actual:/).filter({hasText:next.toFixed(2)}).waitFor();const after=await canvas.evaluate(node=>node.toDataURL());assert.notEqual(after,before);
});

test('cymatics rejects unsafe live controls and updates volume during existing playback', {timeout:45000}, async t=>{
  const page=await fixture(t);await page.getByRole('button',{name:'Escuchar tono'}).click();await page.getByRole('button',{name:'Detener sonido'}).waitFor();const volume=page.getByRole('slider',{name:'Volumen cimático'});await volume.evaluate(node=>{node.value='.41';node.dispatchEvent(new Event('input',{bubbles:true}));});assert.match(await page.getByText(/Volumen de escucha/).innerText(),/41%/);const right=page.getByRole('spinbutton',{name:'Frecuencia del canal derecho'}),before=await right.inputValue();await right.evaluate(node=>{node.value='2200';node.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await right.inputValue(),before);assert.match(await page.getByRole('status').filter({hasText:/canal derecho/}).last().innerText(),/0.1 y 2000 Hz/);await page.getByRole('button',{name:'Detener sonido'}).click();
  await page.getByText('Superficie, excitación y visual',{exact:true}).click();await page.getByRole('spinbutton',{name:'Amortiguamiento cimático'}).evaluate(node=>{node.value='0';node.dispatchEvent(new Event('input',{bubbles:true}));});assert.match(await page.getByRole('status').filter({hasText:/amortiguamiento/}).last().innerText(),/0.001 y 0.3/);
});
