import { test } from 'node:test';
import assert from 'node:assert/strict';
import { BESSEL_ROOTS, besselJ, buildModes, buildResonanceExamples, computeModalField, defaultCymaticsConfig, membraneFrequencyHz, squarePlateFrequencyHz } from '../src/lib/cymatics/physics';
import { createParticles, meanParticlePotential, particlesInBounds, stepParticles } from '../src/lib/cymatics/particles';
import { CYMATICS_STORAGE_KEY, parseCymaticsImport, readCymaticsGallery, saveCymaticsFigure, validateCymaticsConfig } from '../src/lib/cymatics/storage';

test('square plate frequency follows formula and scaling',()=>{const c=defaultCymaticsConfig(),f=squarePlateFrequencyHz(1,1,c);assert.ok(f>0);const wide=structuredClone(c);wide.dimensionsSI.widthM*=2;wide.dimensionsSI.heightM*=2;assert.ok(Math.abs(squarePlateFrequencyHz(1,1,wide)/f-.25)<1e-12);const thick=structuredClone(c);thick.dimensionsSI.thicknessM*=2;assert.ok(Math.abs(squarePlateFrequencyHz(1,1,thick)/f-2)<1e-12);});
test('verified Bessel roots are nodal and membrane scales with radius, tension and density',()=>{assert.ok(Math.abs(besselJ(0,BESSEL_ROOTS[0][0]))<1e-8);assert.ok(Math.abs(besselJ(2,BESSEL_ROOTS[2][0]))<1e-8);const c=defaultCymaticsConfig();c.surfaceType='circular-membrane';c.boundaryCondition='fixed-edge';const f=membraneFrequencyHz(0,1,c),large=structuredClone(c);large.dimensionsSI.radiusM*=2;assert.ok(Math.abs(membraneFrequencyHz(0,1,large)/f-.5)<1e-12);const tense=structuredClone(c);tense.materialSI.tensionNm*=4;assert.ok(Math.abs(membraneFrequencyHz(0,1,tense)/f-2)<1e-12);});
test('degenerate membrane orientations, displaced excitation and finite damped field',()=>{const c=defaultCymaticsConfig();c.surfaceType='circular-membrane';c.boundaryCondition='fixed-edge';const modes=buildModes(c);assert.equal(modes.length,45);const field=computeModalField(c,modes[0].frequencyHz,32);assert.ok(field.values.every(Number.isFinite));assert.ok(Number.isFinite(field.maxAmplitude));assert.ok(field.maxAmplitude>0);});
test('field is deterministic, surface-dependent and invalid frequencies are rejected',()=>{const plate=defaultCymaticsConfig(),a=computeModalField(plate,432,24),b=computeModalField(plate,432,24);assert.deepEqual([...a.values],[...b.values]);const membrane=structuredClone(plate);membrane.surfaceType='circular-membrane';membrane.boundaryCondition='fixed-edge';assert.notDeepEqual([...a.values],[...computeModalField(membrane,432,24).values]);assert.throws(()=>computeModalField(plate,Infinity));assert.throws(()=>computeModalField(plate,3000));});
test('three resonance demonstrations use exact computed modes with useful coupling and distinct fields',()=>{const examples=buildResonanceExamples();assert.equal(examples.length,3);assert.equal(new Set(examples.map(row=>row.modeId)).size,3);const signatures=examples.map(row=>{const mode=buildModes(row.config).find(candidate=>candidate.modeId===row.modeId);assert.ok(mode);assert.ok(Math.abs(mode.coupling)>.08);assert.equal(row.frequencyHz,mode.frequencyHz);assert.equal(row.config.channelFrequenciesHz[0],mode.frequencyHz);const field=computeModalField(row.config,row.frequencyHz,32);assert.equal(field.status,'resonant');return [...field.values].filter((_,index)=>index%31===0).map(value=>value.toExponential(3)).join(',');});assert.equal(new Set(signatures).size,3);});
test('particle integration is deterministic, finite, bounded and descends toward low amplitude in four illustrative seconds',()=>{for(const example of buildResonanceExamples()){const field=computeModalField(example.config,example.frequencyHz,64),a=createParticles(example.config.particleSeed,240,example.config.surfaceType),b=createParticles(example.config.particleSeed,240,example.config.surfaceType),before=meanParticlePotential(a,field);for(let i=0;i<480;i++){stepParticles(a,field,example.config.surfaceType,1/120);stepParticles(b,field,example.config.surfaceType,1/120);}assert.deepEqual(a,b);assert.ok(particlesInBounds(a,example.config.surfaceType));assert.ok(meanParticlePotential(a,field)<before*.78,`${example.id} should reveal lower-amplitude structure`);}});
class Memory { data=new Map<string,string>();getItem(k:string){return this.data.get(k)??null;}setItem(k:string,v:string){this.data.set(k,v);} }
test('gallery validates, roundtrips, preserves corrupt storage and rejects incompatible models',()=>{const m=new Memory(),c=defaultCymaticsConfig();saveCymaticsFigure(c,m as unknown as Storage);assert.deepEqual(readCymaticsGallery(m as unknown as Storage),[c]);assert.equal(m.data.has(CYMATICS_STORAGE_KEY),true);const before='{bad';m.data.set(CYMATICS_STORAGE_KEY,before);assert.throws(()=>saveCymaticsFigure({...c,id:'other'},m as unknown as Storage));assert.equal(m.data.get(CYMATICS_STORAGE_KEY),before);const old={...c,modelVersion:'other'};assert.throws(()=>validateCymaticsConfig(old));assert.throws(()=>parseCymaticsImport('x'.repeat(100001)));});
