'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { buildResonanceExamples, computeModalField, defaultCymaticsConfig, nearestMode, surfaceLabel, AUDIO_MAX_HZ, AUDIO_MIN_HZ } from '@/lib/cymatics/physics';
import { parseCymaticsImport, readCymaticsGallery, saveCymaticsFigure } from '@/lib/cymatics/storage';
import { playCymaticsAudio, setCymaticsFrequency, stopCymaticsAudio } from '@/lib/cymatics/audioAdapter';
import type { CymaticsConfigV1 } from '@/lib/cymatics/types';
import CymaticsCanvas from './CymaticsCanvas';
import styles from './cymatics.module.css';
import { FHPageHeader, FHPageShell, FHSurface } from '@/components/ui/FHLayout';
import { useSearchParams } from 'next/navigation';

const clone=(c:CymaticsConfigV1):CymaticsConfigV1=>structuredClone(c);
const statusText={weak:'Respuesta débil con la escala física actual.',mixed:'Varios modos cercanos contribuyen a la respuesta.',resonant:'Frecuencia cercana a una resonancia modelada.','outside-modeled-range':'Frecuencia fuera del rango modal calculado; no se inventa una figura.'};
export default function CymaticsLab(){
  const search=useSearchParams();
  const [config,setConfig]=useState<CymaticsConfigV1>(()=>{const c=defaultCymaticsConfig(),hz=Number(search.get('frequency')),difference=Number(search.get('binaural')||0),waveform=search.get('waveform');if(Number.isFinite(hz)&&hz>=AUDIO_MIN_HZ&&hz<=AUDIO_MAX_HZ){c.channelFrequenciesHz=difference>0?[hz,hz+difference]:[hz];c.audioMode=difference>0?'binaural':'mono';c.modeledComponents=[hz];if(['sine','square','triangle','sawtooth'].includes(waveform||''))c.waveform=waveform as CymaticsConfigV1['waveform'];}return c;}),[playing,setPlaying]=useState(false),[hidden,setHidden]=useState(false),[volume,setVolume]=useState(.25),[gallery,setGallery]=useState<CymaticsConfigV1[]>(()=>{try{return typeof localStorage==='undefined'?[]:readCymaticsGallery();}catch{return[];}}),[message,setMessage]=useState(''),[a,setA]=useState<CymaticsConfigV1|null>(null),[b,setB]=useState<CymaticsConfigV1|null>(null),[compare,setCompare]=useState(false),[showContours,setShowContours]=useState(true),[resetToken,setResetToken]=useState(0),[exampleId,setExampleId]=useState('plate-2-2'),[activeExample,setActiveExample]=useState<string|null>(null);
  const [sweep,setSweep]=useState({start:100,end:800,duration:30,logarithmic:false,running:false,paused:false});const sweepRef=useRef<{started:number;elapsed:number;raf:number}|null>(null),canvas=useRef<HTMLCanvasElement>(null);
  const patch=(value:Partial<CymaticsConfigV1>)=>setConfig(c=>({...c,...value}));const frequency=config.channelFrequenciesHz[0];
  const examples=useMemo(()=>buildResonanceExamples(),[]);
  const fields=useMemo(()=>config.channelFrequenciesHz.map(f=>computeModalField(config,f,config.renderQuality==='low'?40:config.renderQuality==='high'?84:64)),[config]);
  const referenceScales=useMemo(()=>fields.map(field=>computeModalField(config,field.nearestResonanceHz,field.size).maxAmplitude),[config,fields]);
  const liveCenter=fields[0].nearestResonanceHz,liveMin=Math.max(AUDIO_MIN_HZ,liveCenter*.82),liveMax=Math.min(AUDIO_MAX_HZ,liveCenter*1.18),detuningPercent=(frequency/liveCenter-1)*100;
  useEffect(()=>()=>{if(sweepRef.current)cancelAnimationFrame(sweepRef.current.raf);stopCymaticsAudio();},[]);
  const changeFrequency=(hz:number)=>{if(!Number.isFinite(hz)||hz<AUDIO_MIN_HZ||hz>AUDIO_MAX_HZ)return;setConfig(c=>({...c,channelFrequenciesHz:c.audioMode==='binaural'?[hz,hz+(c.channelFrequenciesHz[1]-c.channelFrequenciesHz[0])]:[hz],modeledComponents:[hz]}));if(playing)setCymaticsFrequency(hz,config.audioMode==='binaural'?hz+(config.channelFrequenciesHz[1]-config.channelFrequenciesHz[0]):undefined);};
  const toggleAudio=()=>{if(playing){stopCymaticsAudio();setPlaying(false);}else{playCymaticsAudio(config,volume);setPlaying(true);}};
  const stopSweep=()=>{if(sweepRef.current)cancelAnimationFrame(sweepRef.current.raf);sweepRef.current=null;setSweep(s=>({...s,running:false,paused:false}));};
  const runSweep=()=>{const start=performance.now(),prior=sweepRef.current?.elapsed??0;sweepRef.current={started:start,elapsed:prior,raf:0};setSweep(s=>({...s,running:true,paused:false}));if(!playing){playCymaticsAudio(config,volume);setPlaying(true);}const tick=(now:number)=>{const elapsed=prior+(now-start)/1000,t=Math.min(1,elapsed/sweep.duration),hz=sweep.logarithmic?sweep.start*(sweep.end/sweep.start)**t:sweep.start+(sweep.end-sweep.start)*t;changeFrequency(hz);if(t<1&&sweepRef.current){sweepRef.current.elapsed=elapsed;sweepRef.current.raf=requestAnimationFrame(tick);}else stopSweep();};sweepRef.current.raf=requestAnimationFrame(tick);};
  const pauseSweep=()=>{if(!sweepRef.current)return;cancelAnimationFrame(sweepRef.current.raf);setSweep(s=>({...s,paused:true}));};
  const save=()=>{try{const row={...clone(config),id:crypto.randomUUID(),createdAt:new Date().toISOString()};saveCymaticsFigure(row);setGallery(readCymaticsGallery());setMessage('Figura guardada de forma reproducible.');}catch(e){setMessage((e as Error).message);}};
  const exportJSON=(c=config)=>{const blob=new Blob([JSON.stringify(c,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`cymatics-${c.id.slice(0,8)}.json`;link.click();URL.revokeObjectURL(url);};
  const exportPNG=()=>{const source=canvas.current;if(!source)return;source.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`cymatics-${config.channelFrequenciesHz.join('-')}hz.png`;link.click();URL.revokeObjectURL(url);});};
  const selectSurface=(surfaceType:CymaticsConfigV1['surfaceType'])=>patch({surfaceType,boundaryCondition:surfaceType==='square-plate'?'simply-supported':'fixed-edge'});
  const applyExample=()=>{const example=examples.find(row=>row.id===exampleId);if(!example)return;const rightDifference=config.audioMode==='binaural'?(config.channelFrequenciesHz[1]??frequency)-frequency:0,next=clone(example.config);next.audioMode=config.audioMode;next.waveform=config.waveform;next.channelFrequenciesHz=config.audioMode==='binaural'?[example.frequencyHz,example.frequencyHz+rightDifference]:[example.frequencyHz];next.modeledComponents=[example.frequencyHz];setConfig(next);setActiveExample(example.id);setResetToken(value=>value+1);if(playing)setCymaticsFrequency(example.frequencyHz,config.audioMode==='binaural'?example.frequencyHz+rightDifference:undefined);setMessage('Resonancia calculada aplicada. El volumen no cambió.');};
  const exploreNearest=()=>{const mode=nearestMode(config,frequency),rightDifference=config.audioMode==='binaural'?(config.channelFrequenciesHz[1]??frequency)-frequency:0;setConfig(current=>({...current,channelFrequenciesHz:current.audioMode==='binaural'?[mode.frequencyHz,mode.frequencyHz+rightDifference]:[mode.frequencyHz],modeledComponents:[mode.frequencyHz]}));setActiveExample(null);setResetToken(value=>value+1);if(playing)setCymaticsFrequency(mode.frequencyHz,config.audioMode==='binaural'?mode.frequencyHz+rightDifference:undefined);setMessage(`Resonancia cercana seleccionada explícitamente: ${mode.modeLabel}.`);};
  return <FHPageShell width="wide" className={styles.lab}><FHPageHeader eyebrow="SIMULACIÓN · EXPLORACIÓN" title="Laboratorio Cimático" description="Explora cómo responde una superficie virtual a tu sonido."/>
    <FHSurface variant="subtle"><strong>Simulación.</strong> La figura depende del sonido y de la superficie virtual. Las partículas son ilustrativas. Esta vista no mide efectos sobre el cuerpo.</FHSurface>
    <FHSurface><h2>Demostración de resonancia</h2><p>Elige uno de tres modos propios calculados. La acción ajusta superficie, frecuencia y punto de excitación para revelar estructura interior; no inicia audio ni cambia el volumen.</p><div className={styles.inline}><label>Figura <select aria-label="Ejemplo de resonancia" value={exampleId} onChange={e=>setExampleId(e.target.value)}>{examples.map(example=><option key={example.id} value={example.id}>{example.title} · {example.modeLabel} · {example.frequencyHz.toFixed(1)} Hz</option>)}</select></label><button onClick={applyExample}>Ver figura de resonancia</button></div>{activeExample&&<p role="status"><strong>{examples.find(row=>row.id===activeExample)?.title}</strong> · {surfaceLabel(config.surfaceType)} · {examples.find(row=>row.id===activeExample)?.modeLabel} · {frequency.toFixed(1)} Hz.</p>}<p><small>Las partículas usan una animación ilustrativa con asentamiento objetivo de 3–5 segundos; no representa tiempo físico medido.</small></p></FHSurface>
    <div className={styles.toolbar}><label>Frecuencia <input aria-label="Frecuencia cimática" type="number" min={AUDIO_MIN_HZ} max={AUDIO_MAX_HZ} step=".1" value={Number(frequency.toFixed(2))} onInput={e=>changeFrequency(Number(e.currentTarget.value))}/> Hz</label><input aria-label="Deslizador de frecuencia cimática" type="range" min="0.1" max="2000" step=".1" value={frequency} onInput={e=>changeFrequency(Number(e.currentTarget.value))}/>
      <label>Superficie <select value={config.surfaceType} onChange={e=>selectSurface(e.target.value as CymaticsConfigV1['surfaceType'])}><option value="square-plate">Placa cuadrada</option><option value="circular-membrane">Membrana circular</option></select></label>
      <label>Vista <select value={config.view} onChange={e=>patch({view:e.target.value as CymaticsConfigV1['view']})}><option value="particles">Partículas ilustrativas</option><option value="vibration">Vibración ilustrativa en vivo</option><option value="field">Campo de amplitud</option><option value="nodal-lines">Contornos de amplitud mínima</option></select></label>
      <button onClick={toggleAudio}>{playing?'Detener sonido':'Escuchar tono'}</button><button onClick={()=>setHidden(v=>!v)}>{hidden?'Mostrar visual':'Ocultar visual'}</button>
    </div>
    <FHSurface variant="subtle"><h2>Exploración en vivo</h2><p>Mueve el control fino y observa cómo cambian la superficie, los contornos y la organización de partículas. Selecciona “Vibración ilustrativa en vivo” para ver la fase calculada ralentizada. Si el sonido está activo, seguirá la frecuencia; este control no inicia audio.</p><label>Alrededor de {liveCenter.toFixed(1)} Hz <input aria-label="Exploración fina de frecuencia" type="range" min={liveMin} max={liveMax} step=".05" value={Math.max(liveMin,Math.min(liveMax,frequency))} onInput={e=>changeFrequency(Number(e.currentTarget.value))}/></label><output aria-live="polite">Frecuencia actual: <strong>{frequency.toFixed(2)} Hz</strong> · distancia al modo: {detuningPercent>=0?'+':''}{detuningPercent.toFixed(2)}%</output><p><small>La fase visual está ralentizada para ser observable; no representa la velocidad física real de vibración.</small></p></FHSurface>
    {config.waveform!=='sine'&&<p role="alert">El audio usa {config.waveform}; el modelo visual MVP representa únicamente su componente fundamental y no los armónicos.</p>}
    <div className={config.audioMode==='binaural'?styles.channels:undefined}>{fields.map((field,i)=><div key={i}><CymaticsCanvas config={config} field={field} label={config.audioMode==='binaural'?(i?'Canal derecho':'Canal izquierdo'):'Simulación cimática'} hidden={hidden} captureRef={i===0?canvas:undefined} showContours={showContours} resetToken={resetToken} scaleMax={referenceScales[i]}/><p className={styles.status} role="status">{statusText[field.status]} Resonancia más cercana: {field.nearestResonanceHz.toFixed(1)} Hz. Rango modal: {field.modeledMinHz.toFixed(1)}–{field.modeledMaxHz.toFixed(1)} Hz. {field.status!=='resonant'&&<button onClick={exploreNearest}>Explorar resonancia cercana</button>}</p></div>)}</div>
    <div className={styles.grid}>
      <FHSurface><h2>Audio y fuerza virtual</h2><label>Volumen de escucha {Math.round(volume*100)}% <input type="range" min="0" max=".6" step=".01" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);}}/></label><label>Fuerza relativa {config.excitationRelativeStrength.toFixed(1)} <input type="range" min=".1" max="3" step=".1" value={config.excitationRelativeStrength} onChange={e=>patch({excitationRelativeStrength:Number(e.target.value)})}/></label><p>Son escalas independientes: el volumen digital no mide fuerza mecánica ni presión acústica.</p><label><input type="checkbox" checked={config.audioMode==='binaural'} onChange={e=>patch({audioMode:e.target.checked?'binaural':'mono',channelFrequenciesHz:e.target.checked?[frequency,frequency+8]:[frequency]})}/> Vista binaural independiente</label>{config.audioMode==='binaural'&&<label>Canal derecho <input type="number" min=".1" max="2000" value={config.channelFrequenciesHz[1]} onChange={e=>patch({channelFrequenciesHz:[frequency,Number(e.target.value)]})}/> Hz <small>Diferencia: {(config.channelFrequenciesHz[1]-frequency).toFixed(1)} Hz; no es un tono emitido.</small></label>}</FHSurface>
      <FHSurface><h2>Barrido lento</h2><div className={styles.inline}><label>Inicio <input type="number" value={sweep.start} onChange={e=>setSweep(s=>({...s,start:Number(e.target.value)}))}/></label><label>Fin <input type="number" value={sweep.end} onChange={e=>setSweep(s=>({...s,end:Number(e.target.value)}))}/></label><label>Segundos <input type="number" min="5" value={sweep.duration} onChange={e=>setSweep(s=>({...s,duration:Number(e.target.value)}))}/></label></div><label><input type="checkbox" checked={sweep.logarithmic} onChange={e=>setSweep(s=>({...s,logarithmic:e.target.checked}))}/> Logarítmico</label><p>Vista: respuesta estacionaria estimada; no representa transitorios.</p><div className={styles.inline}><button disabled={sweep.running&&!sweep.paused} onClick={runSweep}>{sweep.paused?'Continuar':'Iniciar barrido'}</button><button disabled={!sweep.running||sweep.paused} onClick={pauseSweep}>Pausar</button><button disabled={!sweep.running} onClick={stopSweep}>Parar</button></div></FHSurface>
      <FHSurface><h2>Comparación A/B</h2><p>Las capturas conservan superficie, dimensiones, excitación, amortiguamiento, escala y semilla.</p><div className={styles.inline}><button onClick={()=>setA(clone(config))}>Guardar A</button><button onClick={()=>setB(clone(config))}>Guardar B</button><button disabled={!a||!b} onClick={()=>setCompare(v=>!v)}>{compare?'Cerrar comparación':'Comparar'}</button></div>{compare&&a&&b&&<Comparison a={a} b={b}/>}</FHSurface>
      <FHSurface><h2>Configuración avanzada</h2><details><summary>Superficie, excitación y visual</summary><label>Amortiguamiento ζ <input type="number" min=".001" max=".3" step=".001" value={config.damping} onChange={e=>patch({damping:Number(e.target.value)})}/></label><label>Excitación X <input type="range" min=".05" max=".95" step=".01" value={config.excitationPosition.x} onChange={e=>patch({excitationPosition:{...config.excitationPosition,x:Number(e.target.value)}})}/></label><label>Excitación Y <input type="range" min=".05" max=".95" step=".01" value={config.excitationPosition.y} onChange={e=>patch({excitationPosition:{...config.excitationPosition,y:Number(e.target.value)}})}/></label><label>Calidad <select value={config.renderQuality} onChange={e=>patch({renderQuality:e.target.value as CymaticsConfigV1['renderQuality']})}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option></select></label><label><input type="checkbox" checked={showContours} onChange={e=>setShowContours(e.target.checked)}/> Superponer contornos de amplitud mínima</label><button type="button" onClick={()=>setResetToken(value=>value+1)}>Reiniciar partículas con la misma semilla</button><label><input type="checkbox" checked={config.autoExposure} onChange={e=>patch({autoExposure:e.target.checked,visualScale:e.target.checked?'auto':'fixed'})}/> Autoexposición visible</label><p>{surfaceLabel(config.surfaceType)}. Expansión modal truncada a {config.modeCutoff}. Envolvente RMS estacionaria. Los contornos indican amplitud mínima en la respuesta compleja; no siempre son nodos exactos.</p></details></FHSurface>
      <FHSurface><h2>Guardar y exportar</h2><label>Título <input value={config.title} maxLength={100} onChange={e=>patch({title:e.target.value})}/></label><div className={styles.inline}><button onClick={save}>Guardar figura</button><button onClick={exportPNG}>Capturar PNG</button><button onClick={()=>exportJSON()}>Exportar JSON</button><label className={styles.file}>Importar JSON<input type="file" accept="application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{setConfig(parseCymaticsImport(await file.text()));setMessage('Configuración importada y validada.');}catch(err){setMessage((err as Error).message);}}}/></label></div>{message&&<p role="status">{message}</p>}<h3>Galería local ({gallery.length})</h3><ul>{gallery.map(row=><li key={row.id}><button onClick={()=>setConfig(clone(row))}>{row.title} · {row.channelFrequenciesHz.join('/')} Hz · cargar</button> <button onClick={()=>exportJSON(row)}>JSON</button></li>)}</ul></FHSurface>
    </div>
    <details className={styles.how}><summary>Cómo funciona</summary><p>El campo se calcula por respuesta forzada y expansión modal compleja. La placa usa teoría de placa delgada isotrópica con bordes simplemente apoyados; la membrana usa funciones de Bessel con borde fijo. El amortiguamiento mantiene finita la resonancia. Las partículas siguen una ilustración determinista de baja energía y omiten impactos, fricción y acoplamiento con el aire.</p><p>Rango de validez: geometrías ideales, material homogéneo, excitación armónica y respuesta estacionaria. No equivale a una placa real con otros apoyos.</p></details>
  </FHPageShell>;
}
function Comparison({a,b}:{a:CymaticsConfigV1;b:CymaticsConfigV1}){const fa=computeModalField(a,a.channelFrequenciesHz[0]),fb=computeModalField(b,b.channelFrequenciesHz[0]),scale=Math.max(fa.maxAmplitude,fb.maxAmplitude)*2;return <div><p>A: {a.channelFrequenciesHz.join('/')} Hz · B: {b.channelFrequenciesHz.join('/')} Hz</p><p>{JSON.stringify(a.dimensionsSI)===JSON.stringify(b.dimensionsSI)&&a.surfaceType===b.surfaceType?'Superficie física idéntica; escala visual común.':'Las configuraciones físicas difieren; revisa antes de interpretar.'}</p><div className={styles.channels}><CymaticsCanvas config={a} field={fa} label="Comparación A" scaleMax={scale}/><CymaticsCanvas config={b} field={fb} label="Comparación B" scaleMax={scale}/></div></div>}
