'use client';
import {useCallback,useLayoutEffect,useMemo,useRef,useState} from 'react';
import type React from 'react';
import {createParticles,particleOrganization,rng,stepParticles} from '@/lib/cymatics/particles';
import {computeIdealZeroContours} from '@/lib/cymatics/physics';
import type {CymaticsConfigV1,ModalField} from '@/lib/cymatics/types';
import styles from './cymatics.module.css';
import CymaticsGLCanvas from './CymaticsGLCanvas';
import type {SandFrames} from './CymaticsGLRenderer';
import type {SandWorkerFrame,SandWorkerMessage} from '@/lib/cymatics/particleWorker';

const SAND_STEP_SECONDS=.1,POUR_BATCH=220;

type Tool='pour'|'tune'|'excitation';
interface Props {config:CymaticsConfigV1;field:ModalField;label:string;hidden?:boolean;captureRef?:React.RefObject<HTMLCanvasElement|null>;scaleMax?:number;showContours?:boolean;resetToken?:number;animateVibration?:boolean;exactNodes?:boolean;interactive?:boolean;force?:number;onFrequencyChange?:(hz:number)=>void;onExcitationChange?:(position:{x:number;y:number})=>void;}
const palette=(t:number)=>`hsl(${218+72*t} ${70+20*t}% ${9+58*t}%)`,displacementPalette=(v:number)=>v>=0?`hsl(184 88% ${12+54*Math.min(1,v)}%)`:`hsl(276 88% ${12+54*Math.min(1,-v)}%)`;
function contourSegments(field:ModalField,threshold=.085){const segments:Array<[number,number,number,number]>=[],s=field.size;for(let y=0;y<s-1;y++)for(let x=0;x<s-1;x++){const values=[field.values[y*s+x],field.values[y*s+x+1],field.values[(y+1)*s+x+1],field.values[(y+1)*s+x]].map(v=>v/Math.max(field.maxAmplitude,1e-20)),points:Array<[number,number]>=[],corners:[[number,number],[number,number],[number,number],[number,number]]=[[x,y],[x+1,y],[x+1,y+1],[x,y+1]];for(let edge=0;edge<4;edge++){const next=(edge+1)%4,a=values[edge],b=values[next];if((a<threshold)!==(b<threshold)){const t=(threshold-a)/(b-a),p=corners[edge],q=corners[next];points.push([(p[0]+(q[0]-p[0])*t+.5)/s,(p[1]+(q[1]-p[1])*t+.5)/s]);}}if(points.length===2)segments.push([points[0][0],points[0][1],points[1][0],points[1][1]]);else if(points.length===4)segments.push([points[0][0],points[0][1],points[1][0],points[1][1]],[points[2][0],points[2][1],points[3][0],points[3][1]]);}return segments;}

export default function CymaticsCanvas({config,field,label,hidden,captureRef,scaleMax,showContours=false,resetToken=0,animateVibration=true,exactNodes=false,interactive=false,force=1,onFrequencyChange,onExcitationChange}:Props){
  const own=useRef<HTMLCanvasElement>(null),canvasRef=captureRef??own,qualityCount=config.renderQuality==='high'?40000:config.renderQuality==='medium'?20000:8000,count=interactive?qualityCount:Math.min(1200,qualityCount),[tool,setTool]=useState<Tool>('tune'),[organization,setOrganization]=useState(0),[webglReady,setWebglReady]=useState(false),[viewTransform,setViewTransform]=useState({zoom:1,x:0,y:0}),drag=useRef<{x:number;hz:number}|null>(null),longPress=useRef<number|null>(null),renderFrame=useRef<(()=>void)|null>(null),touches=useRef(new Map<number,{x:number;y:number}>()),pinch=useRef<{distance:number;zoom:number;centerX:number;centerY:number}|null>(null),workerActive=useRef(false),worker=useRef<Worker|null>(null),frames=useRef<SandFrames|null>(null),particlesRef=useRef<ReturnType<typeof createParticles>>([]),expectedGeneration=useRef(0),pours=useRef(0),latest=useRef({field,force,surface:config.surfaceType});
  // Frequency/field intentionally are not dependencies: grains migrate instead of resetting.
  const particles=useMemo(()=>{void resetToken;return createParticles(config.particleSeed,count,config.surfaceType);},[config.particleSeed,config.surfaceType,count,resetToken]),contours=useMemo(()=>exactNodes?computeIdealZeroContours(field,config.surfaceType):contourSegments(field),[config.surfaceType,exactNodes,field]);
  useLayoutEffect(()=>{particlesRef.current=particles;latest.current={field,force,surface:config.surfaceType};},[config.surfaceType,field,force,particles]);
  // Replace/pour bump the worker generation; frames still in flight from an older generation are ignored.
  const send=useCallback((message:SandWorkerMessage)=>{const target=worker.current;if(!target)return;if(message.type==='replace'||message.type==='pour'){expectedGeneration.current++;frames.current=null;}target.postMessage(message);},[]);
  const scatter=useCallback(()=>{pours.current++;particles.splice(0,particles.length,...createParticles((config.particleSeed+pours.current*7919)>>>0,count,config.surfaceType));send({type:'replace',particles});renderFrame.current?.();},[config.particleSeed,config.surfaceType,count,particles,send]);
  const point=(event:React.PointerEvent<HTMLCanvasElement>)=>{const canvas=event.currentTarget,rect=canvas.getBoundingClientRect(),side=Math.min(rect.width,rect.height)*.9,ox=(rect.width-side)/2,oy=(rect.height-side)/2;return{x:Math.max(.035,Math.min(.965,(event.clientX-rect.left-ox)/side)),y:Math.max(.035,Math.min(.965,(event.clientY-rect.top-oy)/side))};};
  // Pouring on a full plate recycles the oldest grains instead of silently doing nothing.
  const pour=(position:{x:number;y:number})=>{pours.current++;const random=rng((config.particleSeed+pours.current*97)>>>0),grains:typeof particles=[];for(let i=0;i<POUR_BATCH;i++){const a=random()*Math.PI*2,r=random()*.035,x=position.x+Math.cos(a)*r,y=position.y+Math.sin(a)*r;if(config.surfaceType==='square-plate'||Math.hypot(x-.5,y-.5)<.465)grains.push({x,y,vx:0,vy:0,flight:0,rngState:(random()*0xffffffff)>>>0,tone:random(),size:.7+random()*.6});}const overflow=particles.length+grains.length-count;if(overflow>0)particles.splice(0,overflow);particles.push(...grains);send({type:'pour',grains,cap:count});};
  const pointerDown=(event:React.PointerEvent<HTMLCanvasElement>)=>{event.currentTarget.setPointerCapture(event.pointerId);touches.current.set(event.pointerId,{x:event.clientX,y:event.clientY});if(touches.current.size===2){const [a,b]=[...touches.current.values()],distance=Math.hypot(a.x-b.x,a.y-b.y);pinch.current={distance,zoom:viewTransform.zoom,centerX:(a.x+b.x)/2,centerY:(a.y+b.y)/2};return;}const p=point(event);drag.current={x:event.clientX,hz:config.channelFrequenciesHz[0]};if(tool==='pour')pour(p);if(tool==='excitation')onExcitationChange?.(p);longPress.current=window.setTimeout(()=>onExcitationChange?.(p),550);};
  const pointerMove=(event:React.PointerEvent<HTMLCanvasElement>)=>{if(touches.current.has(event.pointerId))touches.current.set(event.pointerId,{x:event.clientX,y:event.clientY});if(touches.current.size===2&&pinch.current){const [a,b]=[...touches.current.values()],distance=Math.hypot(a.x-b.x,a.y-b.y),zoom=Math.max(1,Math.min(4,pinch.current.zoom*distance/pinch.current.distance)),centerX=(a.x+b.x)/2,centerY=(a.y+b.y)/2;setViewTransform(current=>({zoom,x:current.x+(centerX-pinch.current!.centerX),y:current.y+(centerY-pinch.current!.centerY)}));return;}if(!drag.current)return;const p=point(event);if(tool==='pour')pour(p);else if(tool==='excitation')onExcitationChange?.(p);else{const rect=event.currentTarget.getBoundingClientRect(),delta=(event.clientX-drag.current.x)/rect.width*.1,on=drag.current.hz*(1+delta),nearest=field.nearestResonanceHz,snapped=Math.abs(on/nearest-1)<=.005?nearest:on;onFrequencyChange?.(Math.max(.1,Math.min(2000,snapped)));}};
  const pointerUp=(event:React.PointerEvent<HTMLCanvasElement>)=>{touches.current.delete(event.pointerId);if(touches.current.size<2)pinch.current=null;drag.current=null;if(longPress.current!==null)window.clearTimeout(longPress.current);longPress.current=null;};
  const keyDown=(event:React.KeyboardEvent<HTMLCanvasElement>)=>{const hz=config.channelFrequenciesHz[0],step=event.shiftKey?1:.1;if(event.key==='ArrowLeft'){event.preventDefault();onFrequencyChange?.(Math.max(.1,hz-step));}if(event.key==='ArrowRight'){event.preventDefault();onFrequencyChange?.(Math.min(2000,hz+step));}if(event.key.toLowerCase()==='r')onFrequencyChange?.(field.nearestResonanceHz);if(event.key.toLowerCase()==='s')scatter();};
  // One persistent worker per interactive plate. Frequency changes only send a new field, so grains keep migrating.
  useLayoutEffect(()=>{if(!interactive||!webglReady||config.view!=='particles'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const instance=new Worker(new URL('../../lib/cymatics/particleWorker.ts',import.meta.url),{type:'module'});worker.current=instance;workerActive.current=true;expectedGeneration.current=0;
    instance.onmessage=(event:MessageEvent<SandWorkerFrame>)=>{const {positions,count:received,generation}=event.data,mirror=particlesRef.current;if(generation!==expectedGeneration.current||received!==mirror.length)return;for(let i=0;i<received;i++){mirror[i].x=positions[i*2];mirror[i].y=positions[i*2+1];}const previous=frames.current;frames.current={previous:previous&&previous.count===received&&previous.generation===generation?previous.current:positions,current:positions,count:received,stamp:performance.now(),stepMs:SAND_STEP_SECONDS*1000,generation};};
    const {field:initialField,force:initialForce,surface}=latest.current;instance.postMessage({type:'init',particles:particlesRef.current,field:initialField,surface,force:initialForce,stepSeconds:SAND_STEP_SECONDS} satisfies SandWorkerMessage);
    return()=>{workerActive.current=false;worker.current=null;frames.current=null;instance.postMessage({type:'stop'} satisfies SandWorkerMessage);instance.terminate();};},[config.view,interactive,webglReady]);
  useLayoutEffect(()=>{worker.current?.postMessage({type:'field',field,surface:config.surfaceType,force} satisfies SandWorkerMessage);},[config.surfaceType,field,force]);
  const mounted=useRef<typeof particles|null>(null);
  useLayoutEffect(()=>{if(mounted.current&&mounted.current!==particles)send({type:'replace',particles});mounted.current=particles;},[particles,send]);
  useLayoutEffect(()=>{
    const canvas=canvasRef.current;if(!canvas||hidden)return;const ctx=canvas.getContext('2d');if(!ctx)return;let raf=0,visible=document.visibilityState==='visible',last=performance.now(),accumulator=0,frame=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,fixedStep=1/10,smooth=document.createElement('canvas');smooth.width=field.size;smooth.height=field.size;const buffer=smooth.getContext('2d');
    const resize=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(320,Math.round(rect.width*dpr));canvas.height=Math.max(240,Math.round(rect.height*dpr));};resize();
    if(reduced&&config.view==='particles')for(let i=0;i<360;i++)stepParticles(particles,field,config.surfaceType,fixedStep,{force});
    const paint=(side:number,ox:number,oy:number,fn:(b:CanvasRenderingContext2D,x:number,y:number)=>void)=>{if(!buffer)return;buffer.clearRect(0,0,field.size,field.size);for(let y=0;y<field.size;y++)for(let x=0;x<field.size;x++)fn(buffer,x,y);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(smooth,ox,oy,side,side);};
    const drawField=(side:number,ox:number,oy:number,opacity=1)=>{const scale=config.autoExposure?Math.max(field.maxAmplitude,1e-20):Math.max(scaleMax??field.maxAmplitude*2,1e-20);ctx.save();ctx.globalAlpha=opacity;paint(side,ox,oy,(b,x,y)=>{const px=(x+.5)/field.size,py=(y+.5)/field.size;if(config.surfaceType==='circular-membrane'&&Math.hypot(px-.5,py-.5)>.5)return;b.fillStyle=palette(Math.min(1,field.values[y*field.size+x]/scale));b.fillRect(x,y,1,1);});ctx.restore();};
    const drawVibration=(side:number,ox:number,oy:number,now:number)=>{const scale=config.autoExposure?Math.max(field.maxAmplitude,1e-20):Math.max(scaleMax??field.maxAmplitude,1e-20),phase=reduced||!animateVibration?0:(now/900)%(Math.PI*2),cos=Math.cos(phase),sin=Math.sin(phase);paint(side,ox,oy,(b,x,y)=>{const px=(x+.5)/field.size,py=(y+.5)/field.size;if(config.surfaceType==='circular-membrane'&&Math.hypot(px-.5,py-.5)>.5)return;const i=y*field.size+x,v=(field.realValues[i]*cos-field.imaginaryValues[i]*sin)/scale;b.fillStyle=displacementPalette(v);b.fillRect(x,y,1,1);});};
    const drawContours=(side:number,ox:number,oy:number)=>{ctx.save();ctx.strokeStyle='#79f4dc';ctx.lineWidth=Math.max(1.4,side/360);ctx.beginPath();for(const [x1,y1,x2,y2] of contours){ctx.moveTo(ox+x1*side,oy+y1*side);ctx.lineTo(ox+x2*side,oy+y2*side);}ctx.stroke();ctx.restore();};
    const render=(now=performance.now())=>{if(!visible)return;const elapsed=Math.min(.12,(now-last)/1000);last=now;if(config.view==='particles'&&!reduced&&!workerActive.current){accumulator+=elapsed;while(accumulator>=fixedStep){stepParticles(particles,field,config.surfaceType,fixedStep,{force});accumulator-=fixedStep;}}const w=canvas.width,h=canvas.height,side=Math.min(w,h)*.9,ox=(w-side)/2,oy=(h-side)/2;ctx.fillStyle='#030711';ctx.fillRect(0,0,w,h);if(config.view==='field')drawField(side,ox,oy);else if(config.view==='vibration'){drawVibration(side,ox,oy,now);if(showContours)drawContours(side,ox,oy);}else if(config.view==='nodal-lines'){drawField(side,ox,oy,.32);drawContours(side,ox,oy);}else{const metal=ctx.createLinearGradient(ox,oy,ox+side,oy+side);metal.addColorStop(0,config.surfaceType==='square-plate'?'#34404c':'#29313b');metal.addColorStop(.5,'#101722');metal.addColorStop(1,'#070b12');ctx.fillStyle=metal;if(config.surfaceType==='circular-membrane'){ctx.beginPath();ctx.arc(w/2,h/2,side/2,0,Math.PI*2);ctx.fill();}else ctx.fillRect(ox,oy,side,side);drawField(side,ox,oy,.12);if(showContours)drawContours(side,ox,oy);if(!webglReady){ctx.fillStyle='#0c0a07';for(const p of particles)ctx.fillRect(ox+p.x*side+1.2,oy+p.y*side+1.2,Math.max(1,p.size*1.7),Math.max(1,p.size*1.7));for(const p of particles){const light=190+Math.round(p.tone*43);ctx.fillStyle=`rgb(${light+10} ${light+1} ${Math.max(140,light-24)})`;ctx.fillRect(ox+p.x*side,oy+p.y*side,Math.max(1,p.size*1.45),Math.max(1,p.size*1.45));}}}ctx.strokeStyle='#73849a';ctx.lineWidth=2;ctx.beginPath();if(config.surfaceType==='circular-membrane')ctx.arc(w/2,h/2,side/2,0,Math.PI*2);else ctx.rect(ox,oy,side,side);ctx.stroke();if(interactive){ctx.strokeStyle='#f7c873';ctx.lineWidth=3;ctx.beginPath();ctx.arc(ox+config.excitationPosition.x*side,oy+config.excitationPosition.y*side,10,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='rgba(2,6,17,.82)';ctx.fillRect(12,h-48,Math.min(w-24,430),34);ctx.fillStyle='#e7f2ff';ctx.font=`${Math.max(12,w/55)}px ui-monospace`;ctx.fillText(`${label} · ${config.channelFrequenciesHz.map(f=>f.toFixed(2)).join(' / ')} Hz`,22,h-26);if(++frame%15===0)setOrganization(particleOrganization(particles,field));if(!reduced&&(config.view==='particles'||config.view==='vibration'))raf=requestAnimationFrame(render);};
    renderFrame.current=()=>render();const observer=new ResizeObserver(()=>{resize();render();});observer.observe(canvas);const visibility=()=>{visible=document.visibilityState==='visible';if(visible){last=performance.now();cancelAnimationFrame(raf);resize();render();}else cancelAnimationFrame(raf);};document.addEventListener('visibilitychange',visibility);render();return()=>{renderFrame.current=null;cancelAnimationFrame(raf);observer.disconnect();document.removeEventListener('visibilitychange',visibility);};
  },[animateVibration,canvasRef,config,contours,field,force,hidden,interactive,label,particles,scaleMax,showContours,webglReady]);
  if(hidden)return <div className={styles.hidden} role="status">Visual pausado y oculto. El audio puede continuar.</div>;
  const canvas=<canvas ref={canvasRef} className={`${styles.canvas} ${webglReady?styles.canvasUnderGL:''}`} role="img" aria-label={label} tabIndex={interactive?0:undefined} onPointerDown={interactive?pointerDown:undefined} onPointerMove={interactive?pointerMove:undefined} onPointerUp={interactive?pointerUp:undefined} onPointerCancel={interactive?pointerUp:undefined} onDoubleClick={interactive?scatter:undefined} onWheel={interactive?event=>{event.preventDefault();setViewTransform(current=>({...current,zoom:Math.max(1,Math.min(4,current.zoom*Math.exp(-event.deltaY*.001)))}));}:undefined} onKeyDown={interactive?keyDown:undefined}/>;
  if(!interactive)return canvas;
  return <div className={styles.interactiveCanvas}><div className={styles.canvasTools} role="toolbar" aria-label="Herramientas de la superficie">{([['pour','Verter arena'],['tune','Afinar'],['excitation','Mover excitación']] as const).map(([id,text])=><button key={id} aria-pressed={tool===id} aria-label={text} onClick={()=>setTool(id)}>{text}</button>)}<button aria-label="Esparcir arena" onClick={scatter}>Esparcir</button><button aria-label="Restablecer zoom" onClick={()=>setViewTransform({zoom:1,x:0,y:0})}>{viewTransform.zoom.toFixed(1)}×</button></div><div className={styles.canvasStage} style={{transform:`translate(${viewTransform.x}px,${viewTransform.y}px) scale(${viewTransform.zoom})`}}>{canvas}{config.view==='particles'&&<CymaticsGLCanvas particles={particles} surface={config.surfaceType} frames={frames} onReady={setWebglReady}/>}</div><div className={styles.canvasHud} aria-live="polite"><strong>{config.channelFrequenciesHz[0].toFixed(2)} Hz</strong><span>Modo cercano {field.nearestResonanceHz.toFixed(2)} Hz</span><span>Distancia {((config.channelFrequenciesHz[0]/field.nearestResonanceHz-1)*100).toFixed(2)}%</span><label>Organización <progress max="1" value={organization}/></label></div></div>;
}
