'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { BESSEL_ROOTS, buildModeMap, buildModes, buildResonanceExamples, computeCircularIdealMode, computeModalField, computeResponseCurve, defaultCymaticsConfig, membraneFrequencyHz, nearestMode, surfaceLabel, AUDIO_MAX_HZ, AUDIO_MIN_HZ } from '@/lib/cymatics/physics';
import { parseCymaticsImport, readCymaticsGallery, saveCymaticsFigure } from '@/lib/cymatics/storage';
import { playCymaticsAudio, setCymaticsFrequency, setCymaticsVolume, stopCymaticsAudio } from '@/lib/cymatics/audioAdapter';
import type { CymaticsConfigV1 } from '@/lib/cymatics/types';
import CymaticsCanvas from './CymaticsCanvas';
import styles from './cymatics.module.css';
import { FHPageHeader, FHPageShell, FHSurface } from '@/components/ui/FHLayout';
import { useSearchParams } from 'next/navigation';
import { GUIDED_CYMATICS_STEPS, advanceGuidedCymaticsSession, endGuidedCymaticsSession, guidedRemainingSeconds, idleGuidedCymaticsSession, pauseGuidedCymaticsSession, resumeGuidedCymaticsSession, skipGuidedCymaticsStep, startGuidedCymaticsSession } from '@/lib/cymatics/session';
import { exportCymaticsJournalCsv } from '@/lib/cymatics/journal';
import { detectPitch } from '@/lib/cymatics/pitch';
import { ConstellationStore } from '@/lib/harmonic/constellationStorage';
import { createHarmonicCymaticsTransfer, selectTransferMembers, transferMemberLabel, type HarmonicCymaticsTransferV1 } from '@/lib/cymatics/harmonicTransfer';

const clone=(c:CymaticsConfigV1):CymaticsConfigV1=>structuredClone(c);
const statusText={weak:'Respuesta débil con la escala física actual.',mixed:'Varios modos cercanos contribuyen a la respuesta.',resonant:'Frecuencia cercana a una resonancia modelada.','outside-modeled-range':'Frecuencia fuera del rango modal calculado; no se inventa una figura.'};
const CYMATICS_UI_KEY='fh:cymatics-ui-v1';
const JOURNAL_30_DAY_CUTOFF=Date.now()-30*86400_000;
function initialDisclosure(){try{const value=JSON.parse(localStorage.getItem(CYMATICS_UI_KEY)??'{}');return {advanced:value.advanced===true,how:value.how===true};}catch{return {advanced:false,how:false};}}
export default function CymaticsLab(){
  const search=useSearchParams();
  const requestedConstellationId=search.get('constellation');
  const [config,setConfig]=useState<CymaticsConfigV1>(()=>{const c=defaultCymaticsConfig(),hz=Number(search.get('frequency')),difference=Number(search.get('binaural')||0),waveform=search.get('waveform');if(Number.isFinite(hz)&&hz>=AUDIO_MIN_HZ&&hz<=AUDIO_MAX_HZ){const validDifference=Number.isFinite(difference)&&difference>0&&hz+difference<=AUDIO_MAX_HZ;c.channelFrequenciesHz=validDifference?[hz,hz+difference]:[hz];c.audioMode=validDifference?'binaural':'mono';c.modeledComponents=[hz];if(['sine','square','triangle','sawtooth'].includes(waveform||''))c.waveform=waveform as CymaticsConfigV1['waveform'];}return c;}),[playing,setPlaying]=useState(false),[hidden,setHidden]=useState(false),[volume,setVolume]=useState(.25),[gallery,setGallery]=useState<CymaticsConfigV1[]>(()=>{try{return typeof localStorage==='undefined'?[]:readCymaticsGallery();}catch{return[];}}),[message,setMessage]=useState(''),[a,setA]=useState<CymaticsConfigV1|null>(null),[b,setB]=useState<CymaticsConfigV1|null>(null),[compare,setCompare]=useState(false),[showContours,setShowContours]=useState(true),[resetToken,setResetToken]=useState(0),[exampleId,setExampleId]=useState('plate-2-2'),[activeExample,setActiveExample]=useState<string|null>(null);
  const [sweep,setSweep]=useState({start:100,end:800,duration:30,logarithmic:false,running:false,paused:false});const sweepRef=useRef<{started:number;elapsed:number;raf:number}|null>(null),canvas=useRef<HTMLCanvasElement>(null);
  const [modeM,setModeM]=useState(2),[modeN,setModeN]=useState(1),[modeRotation,setModeRotation]=useState(0),[modeView,setModeView]=useState<'ideal'|'forced'>('ideal'),[animateMode,setAnimateMode]=useState(false);
  const [guided,setGuided]=useState(idleGuidedCymaticsSession),[guidedJournalOpen,setGuidedJournalOpen]=useState(false),[guidedPng,setGuidedPng]=useState<string|null>(null),[reducedMotion,setReducedMotion]=useState(false);const guidedCapture=useRef(false);
  const [calm,setCalm]=useState(5),[journalNote,setJournalNote]=useState('');
  const [microphone,setMicrophone]=useState<'off'|'requesting'|'active'>('off'),[detectedHz,setDetectedHz]=useState<number|null>(null);
  const microphoneRef=useRef<{stream:MediaStream;context:AudioContext;raf:number}|null>(null),microphoneHz=useRef<number|null>(null);
  const [disclosure,setDisclosure]=useState(initialDisclosure);
  const [harmonicTransfer,setHarmonicTransfer]=useState<HarmonicCymaticsTransferV1|null>(null),[transferSelection,setTransferSelection]=useState<string[]>([]),[transferError,setTransferError]=useState('');
  const patch=(value:Partial<CymaticsConfigV1>)=>setConfig(c=>({...c,...value}));const frequency=config.channelFrequenciesHz[0];
  const examples=useMemo(()=>buildResonanceExamples(),[]);
  const fields=useMemo(()=>config.channelFrequenciesHz.map(f=>computeModalField(config,f,config.renderQuality==='low'?40:config.renderQuality==='high'?84:64)),[config]);
  const referenceScales=useMemo(()=>fields.map(field=>computeModalField(config,field.nearestResonanceHz,field.size).maxAmplitude),[config,fields]);
  const liveCenter=fields[0].nearestResonanceHz,liveMin=Math.max(AUDIO_MIN_HZ,liveCenter*.82),liveMax=Math.min(AUDIO_MAX_HZ,liveCenter*1.18),detuningPercent=(frequency/liveCenter-1)*100;
  const idealConfig=clone(config);idealConfig.surfaceType='circular-membrane';idealConfig.boundaryCondition='fixed-edge';idealConfig.audioMode='mono';idealConfig.view='vibration';idealConfig.autoExposure=true;const idealFrequency=membraneFrequencyHz(modeM,modeN,idealConfig);idealConfig.channelFrequenciesHz=[idealFrequency];idealConfig.modeledComponents=[idealFrequency];const idealField=computeCircularIdealMode(idealConfig,modeM,modeN,modeRotation*Math.PI/180,96);
  useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReducedMotion(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
  useEffect(()=>{if(!requestedConstellationId)return;let active=true;void (async()=>{try{const rows=await new ConstellationStore(localStorage).load(),source=rows.find(row=>row.id===requestedConstellationId);if(!source)throw new Error('La constelación solicitada no está disponible en este dispositivo.');const transfer=await createHarmonicCymaticsTransfer(source);if(active){setHarmonicTransfer(transfer);setTransferSelection([]);setTransferError('');}}catch(error){if(active)setTransferError(error instanceof Error?error.message:'No se pudo validar la constelación.');}})();return()=>{active=false;};},[requestedConstellationId]);
  const stopMicrophone=()=>{const active=microphoneRef.current;if(active){cancelAnimationFrame(active.raf);active.stream.getTracks().forEach(track=>track.stop());void active.context.close();microphoneRef.current=null;}microphoneHz.current=null;setDetectedHz(null);setMicrophone('off');};
  useEffect(()=>()=>{if(sweepRef.current)cancelAnimationFrame(sweepRef.current.raf);stopCymaticsAudio();const active=microphoneRef.current;if(active){cancelAnimationFrame(active.raf);active.stream.getTracks().forEach(track=>track.stop());void active.context.close();}},[]);
  useEffect(()=>{if(guided.status!=='running')return;let prior=performance.now();const timer=window.setInterval(()=>{const now=performance.now(),delta=(now-prior)/1000;prior=now;setGuided(state=>advanceGuidedCymaticsSession(state,delta));},250);return()=>clearInterval(timer);},[guided.status]);
  const changeFrequency=(hz:number)=>{const difference=config.audioMode==='binaural'?(config.channelFrequenciesHz[1]??frequency)-frequency:0,right=hz+difference;if(!Number.isFinite(hz)||hz<AUDIO_MIN_HZ||hz>AUDIO_MAX_HZ||config.audioMode==='binaural'&&right>AUDIO_MAX_HZ){setMessage('La frecuencia solicitada dejaría un canal fuera de 0.1–2000 Hz. No se modificó.');return;}setConfig(c=>({...c,channelFrequenciesHz:c.audioMode==='binaural'?[hz,right]:[hz],modeledComponents:[hz]}));setActiveExample(null);if(playing)setCymaticsFrequency(hz,config.audioMode==='binaural'?right:undefined);};
  const changeRightFrequency=(right:number)=>{if(!Number.isFinite(right)||right<AUDIO_MIN_HZ||right>AUDIO_MAX_HZ||right<=frequency){setMessage('El canal derecho debe ser mayor que el izquierdo y permanecer entre 0.1 y 2000 Hz.');return;}patch({channelFrequenciesHz:[frequency,right]});if(playing)setCymaticsFrequency(frequency,right);};
  const toggleBinaural=(enabled:boolean)=>{if(!enabled){patch({audioMode:'mono',channelFrequenciesHz:[frequency]});if(playing)setCymaticsFrequency(frequency);return;}if(frequency+8>AUDIO_MAX_HZ){setMessage('Reduce la frecuencia izquierda antes de activar una diferencia binaural de 8 Hz.');return;}patch({audioMode:'binaural',channelFrequenciesHz:[frequency,frequency+8]});if(playing)setCymaticsFrequency(frequency,frequency+8);};
  const toggleAudio=async()=>{if(playing){stopCymaticsAudio();setPlaying(false);}else try{const started=await playCymaticsAudio(config,volume);setPlaying(started);if(started)setMessage('');}catch(error){setPlaying(false);setMessage(error instanceof Error?error.message:'No se pudo iniciar el sonido.');}};
  const applyTransferFrequency=(memberId:string)=>{if(!harmonicTransfer)return;try{const [member]=selectTransferMembers(harmonicTransfer,[memberId]);stopSweep();stopCymaticsAudio();setPlaying(false);setConfig(current=>({...current,audioMode:'mono',channelFrequenciesHz:[member.frequencyHz],modeledComponents:[member.frequencyHz]}));setActiveExample(null);setMessage(`${member.frequencyHz.toFixed(2)} Hz cargados para análisis. El audio permanece apagado.`);}catch(error){setTransferError((error as Error).message);}};
  const prepareTransferComparison=()=>{if(!harmonicTransfer)return;try{const [first,second]=selectTransferMembers(harmonicTransfer,transferSelection,2);if(!second)throw new Error('Selecciona exactamente dos miembros para comparar.');stopSweep();stopCymaticsAudio();setPlaying(false);const left=clone(config),right=clone(config);for(const [target,member] of [[left,first],[right,second]] as const){target.audioMode='mono';target.channelFrequenciesHz=[member.frequencyHz];target.modeledComponents=[member.frequencyHz];target.autoExposure=false;target.visualScale='fixed';}setA(left);setB(right);setCompare(true);setMessage('Comparación armónica preparada. Solo cambia la frecuencia; el audio permanece apagado.');}catch(error){setTransferError((error as Error).message);}};
  const startMicrophone=async()=>{if(microphone!=='off')return;setMicrophone('requesting');stopCymaticsAudio();setPlaying(false);try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}}),context=new AudioContext(),source=context.createMediaStreamSource(stream),analyser=context.createAnalyser();analyser.fftSize=4096;source.connect(analyser);const samples=new Float32Array(analyser.fftSize),active={stream,context,raf:0};microphoneRef.current=active;setMicrophone('active');const tick=()=>{if(microphoneRef.current!==active)return;analyser.getFloatTimeDomainData(samples);const result=detectPitch(samples,context.sampleRate);if(result){const prior=microphoneHz.current??result.frequencyHz,alpha=1-Math.exp(-1/9),next=prior+(result.frequencyHz-prior)*alpha;microphoneHz.current=next;setDetectedHz(next);changeFrequency(next);patch({excitationRelativeStrength:Math.max(.1,Math.min(3,result.rms*10))});}active.raf=requestAnimationFrame(tick);};active.raf=requestAnimationFrame(tick);}catch(error){stopMicrophone();setMessage(error instanceof Error?`No se pudo activar el micrófono: ${error.message}`:'No se pudo activar el micrófono.');}};
  const stopSweep=()=>{if(sweepRef.current)cancelAnimationFrame(sweepRef.current.raf);sweepRef.current=null;setSweep(s=>({...s,running:false,paused:false}));};
  const runSweep=(start:number)=>{const difference=config.audioMode==='binaural'?(config.channelFrequenciesHz[1]??frequency)-frequency:0;if(!Number.isFinite(sweep.start)||!Number.isFinite(sweep.end)||!Number.isFinite(sweep.duration)||sweep.start<AUDIO_MIN_HZ||sweep.end<=sweep.start||sweep.end+difference>AUDIO_MAX_HZ||sweep.duration<5||sweep.duration>3600){setMessage('Barrido inválido: usa un inicio menor al final, 5–3600 segundos y mantén ambos canales entre 0.1 y 2000 Hz.');return;}const prior=sweepRef.current?.elapsed??0;sweepRef.current={started:start,elapsed:prior,raf:0};setSweep(s=>({...s,running:true,paused:false}));const tick=(now:number)=>{const elapsed=prior+(now-start)/1000,t=Math.min(1,elapsed/sweep.duration),hz=sweep.logarithmic?sweep.start*(sweep.end/sweep.start)**t:sweep.start+(sweep.end-sweep.start)*t;changeFrequency(hz);if(t<1&&sweepRef.current){sweepRef.current.elapsed=elapsed;sweepRef.current.raf=requestAnimationFrame(tick);}else stopSweep();};sweepRef.current.raf=requestAnimationFrame(tick);};
  const pauseSweep=()=>{if(!sweepRef.current)return;cancelAnimationFrame(sweepRef.current.raf);setSweep(s=>({...s,paused:true}));};
  const stopAll=()=>{stopSweep();stopCymaticsAudio();stopMicrophone();setPlaying(false);setGuided(state=>state.status==='idle'||state.status==='complete'?state:endGuidedCymaticsSession(state));setMessage('Barrido, audio, micrófono y sesión guiada detenidos.');};
  const save=()=>{try{const createdAt=new Date().toISOString(),row={...clone(config),id:crypto.randomUUID(),createdAt,journal:{createdAt,calm,note:journalNote,...(guidedJournalOpen&&guided.sessionId?{sessionId:guided.sessionId}:{})}};saveCymaticsFigure(row);setGallery(readCymaticsGallery());setMessage('Figura y práctica guardadas de forma reproducible.');}catch(e){setMessage((e as Error).message);}};
  const exportJSON=(c=config)=>{const blob=new Blob([JSON.stringify(c,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`cymatics-${c.id.slice(0,8)}.json`;link.click();URL.revokeObjectURL(url);};
  const exportPNG=()=>{const source=canvas.current;if(!source)return;source.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`cymatics-${config.channelFrequenciesHz.join('-')}hz.png`;link.click();URL.revokeObjectURL(url);});};
  const exportJournalCsv=()=>{const blob=new Blob([exportCymaticsJournalCsv(gallery)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='resonance-lab-diario-cimatico.csv';link.click();URL.revokeObjectURL(url);};
  const selectSurface=(surfaceType:CymaticsConfigV1['surfaceType'])=>patch({surfaceType,boundaryCondition:surfaceType==='square-plate'?'simply-supported':'fixed-edge'});
  const applyExample=()=>{const example=examples.find(row=>row.id===exampleId);if(!example)return;const rightDifference=config.audioMode==='binaural'?(config.channelFrequenciesHz[1]??frequency)-frequency:0,right=example.frequencyHz+rightDifference;if(right>AUDIO_MAX_HZ){setMessage('Este ejemplo dejaría el canal derecho fuera de rango. Reduce primero la diferencia binaural.');return;}const next=clone(example.config);next.audioMode=config.audioMode;next.waveform=config.waveform;next.channelFrequenciesHz=config.audioMode==='binaural'?[example.frequencyHz,right]:[example.frequencyHz];next.modeledComponents=[example.frequencyHz];setConfig(next);setActiveExample(example.id);setResetToken(value=>value+1);if(playing)setCymaticsFrequency(example.frequencyHz,config.audioMode==='binaural'?right:undefined);setMessage('Resonancia calculada aplicada. El volumen no cambió.');};
  const listenExample=async(id:string)=>{const example=examples.find(row=>row.id===id);if(!example)return;stopSweep();stopCymaticsAudio();const next=clone(example.config);setExampleId(id);setConfig(next);setActiveExample(id);setResetToken(value=>value+1);try{setPlaying(await playCymaticsAudio(next,volume));}catch(error){setPlaying(false);setMessage(error instanceof Error?error.message:'No se pudo iniciar el sonido.');}};
  const setDisclosureOpen=(key:'advanced'|'how',open:boolean)=>{const next={...disclosure,[key]:open};setDisclosure(next);try{localStorage.setItem(CYMATICS_UI_KEY,JSON.stringify(next));}catch{/* La interfaz funciona aunque el almacenamiento no esté disponible. */}};
  const exploreNearest=()=>{const mode=nearestMode(config,frequency),rightDifference=config.audioMode==='binaural'?(config.channelFrequenciesHz[1]??frequency)-frequency:0,right=mode.frequencyHz+rightDifference;if(right>AUDIO_MAX_HZ){setMessage('La resonancia cercana dejaría el canal derecho fuera de rango. Reduce primero la diferencia binaural.');return;}setConfig(current=>({...current,channelFrequenciesHz:current.audioMode==='binaural'?[mode.frequencyHz,right]:[mode.frequencyHz],modeledComponents:[mode.frequencyHz]}));setActiveExample(null);if(playing)setCymaticsFrequency(mode.frequencyHz,config.audioMode==='binaural'?right:undefined);setMessage(`Resonancia cercana seleccionada explícitamente: ${mode.modeLabel}.`);};
  const prepareGuide=()=>{const example=examples[0],peak=example.frequencyHz,next=clone(example.config);next.autoExposure=false;next.visualScale='fixed';next.view='field';setModeView('ideal');setConfig(next);setSweep({start:peak*.86,end:peak*1.14,duration:20,logarithmic:false,running:false,paused:false});setA(null);setB(null);setCompare(false);setMessage('Experimento de placa preparado. El explorador superior volvió a Modo ideal; el audio permanece apagado.');};
  const comparePeak=()=>{const mode=nearestMode(config,frequency),near=clone(config),far=clone(config),difference=config.audioMode==='binaural'?(config.channelFrequenciesHz[1]??frequency)-frequency:0;near.channelFrequenciesHz=config.audioMode==='binaural'?[mode.frequencyHz,mode.frequencyHz+difference]:[mode.frequencyHz];near.modeledComponents=[mode.frequencyHz];const away=Math.max(AUDIO_MIN_HZ,mode.frequencyHz*.86);far.channelFrequenciesHz=config.audioMode==='binaural'?[away,away+difference]:[away];far.modeledComponents=[away];near.autoExposure=false;far.autoExposure=false;near.visualScale='fixed';far.visualScale='fixed';setA(near);setB(far);setCompare(true);setMessage('Comparación preparada: solo cambia la frecuencia; la escala visual es común.');};
  const applyIdealToForced=()=>{const difference=config.audioMode==='binaural'?(config.channelFrequenciesHz[1]??frequency)-frequency:0;if(idealFrequency+difference>AUDIO_MAX_HZ){setMessage('Este modo dejaría el canal derecho fuera del rango de audio. Reduce primero la diferencia binaural.');return;}setConfig(current=>({...current,surfaceType:'circular-membrane',boundaryCondition:'fixed-edge',channelFrequenciesHz:current.audioMode==='binaural'?[idealFrequency,idealFrequency+difference]:[idealFrequency],modeledComponents:[idealFrequency],view:'field',autoExposure:false}));setModeView('forced');setActiveExample(null);setResetToken(value=>value+1);if(playing)setCymaticsFrequency(idealFrequency,config.audioMode==='binaural'?idealFrequency+difference:undefined);setMessage('Modo aplicado a la respuesta forzada. El audio no se inició.');};
  const startGuidedAudio=async(next:CymaticsConfigV1,level:number)=>{stopCymaticsAudio();setPlaying(false);try{const started=await playCymaticsAudio(next,Math.min(.25,level));setPlaying(started);}catch(error){setMessage(error instanceof Error?error.message:'No se pudo iniciar el sonido guiado.');}};
  const startGuided=()=>{stopSweep();stopCymaticsAudio();setPlaying(false);setVolume(.2);guidedCapture.current=false;setGuidedPng(null);setGuidedJournalOpen(false);setGuided(startGuidedCymaticsSession(crypto.randomUUID()));};
  const guidedStep=guided.status==='idle'?null:GUIDED_CYMATICS_STEPS[guided.stepIndex];
  useEffect(()=>{if(!guidedStep)return;let cancelled=false;queueMicrotask(()=>{if(cancelled)return;const id=guidedStep.id;if(id==='preparation'){stopSweep();stopCymaticsAudio();setPlaying(false);setVolume(.2);setMessage('Siéntate, pantalla a la altura de los ojos.');}else if(id==='anchor'){const example=examples.find(row=>row.id==='membrane-0-2-cos');if(example){const next=clone(example.config);next.view=reducedMotion?'field':'vibration';setConfig(next);setActiveExample(example.id);setVolume(.2);void startGuidedAudio(next,.2);}}else if(id==='sweep'){stopCymaticsAudio();setPlaying(false);const next={start:150,end:450,duration:180,logarithmic:true,running:false,paused:false};setSweep(next);const started=performance.now();sweepRef.current={started,elapsed:0,raf:0};const tick=(now:number)=>{const elapsed=(now-started)/1000,t=Math.min(1,elapsed/180),hz=150*(450/150)**t;changeFrequency(hz);if(t<1&&sweepRef.current){sweepRef.current.elapsed=elapsed;sweepRef.current.raf=requestAnimationFrame(tick);}else stopSweep();};sweepRef.current.raf=requestAnimationFrame(tick);setSweep({...next,running:true});}else if(id==='stillness'){stopSweep();const example=examples.find(row=>row.id==='membrane-3-1-cos');if(example){const next=clone(example.config);next.view=reducedMotion?'field':'vibration';setConfig(next);setActiveExample(example.id);setVolume(.15);void startGuidedAudio(next,.15);}}else if(id==='record'){stopCymaticsAudio();setPlaying(false);if(!guidedCapture.current){guidedCapture.current=true;setGuidedPng(canvas.current?.toDataURL('image/png')??null);}}else if(id==='close'){stopSweep();stopCymaticsAudio();setPlaying(false);setGuidedJournalOpen(true);}});return()=>{cancelled=true;};
  // Step actions intentionally execute once per state-machine transition.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[guided.stepIndex]);
  useEffect(()=>{const onVisibility=()=>{if(document.hidden){setGuided(state=>pauseGuidedCymaticsSession(state));stopSweep();stopCymaticsAudio();stopMicrophone();setPlaying(false);}};document.addEventListener('visibilitychange',onVisibility);return()=>document.removeEventListener('visibilitychange',onVisibility);},[]);
  return <FHPageShell width="wide" className={styles.lab}><FHPageHeader eyebrow="SIMULACIÓN · EXPLORACIÓN" title="Laboratorio de Resonancia" description="Escucha, observa y compara cómo responden superficies virtuales al sonido."/>
    {(harmonicTransfer||transferError)&&<FHSurface className={styles.harmonicTransfer}><p className={styles.kicker}>DESDE LABORATORIO ARMÓNICO</p><h2>Revisar constelación antes de analizar</h2>{transferError?<p role="alert">{transferError} No se modificó la configuración ni se inició audio.</p>:harmonicTransfer&&<><p><strong>{harmonicTransfer.name||'Constelación sin nombre'}</strong> · semilla {harmonicTransfer.seedFrequencyHz.toFixed(2)} Hz · {harmonicTransfer.playbackMode==='sequence'?'secuencia':'simultánea'}</p><p>Estas frecuencias son excitaciones candidatas. No se convierten en modos propios ni se promedian. Elige una para el campo actual o dos para A/B bajo las mismas condiciones físicas.</p><ol className={styles.transferMembers}>{harmonicTransfer.members.map((member,index)=><li key={member.id}><label><input type="checkbox" checked={transferSelection.includes(member.id)} onChange={event=>setTransferSelection(selected=>event.target.checked?(selected.length<2?[...selected,member.id]:selected):selected.filter(id=>id!==member.id))}/><span>{index+1}. {transferMemberLabel(member)} · <strong>{member.frequencyHz.toFixed(2)} Hz</strong></span></label><button type="button" onClick={()=>applyTransferFrequency(member.id)}>Usar esta frecuencia</button></li>)}</ol><div className={styles.inline}><button type="button" disabled={transferSelection.length!==2} onClick={prepareTransferComparison}>Preparar comparación A/B</button><button type="button" onClick={()=>{setHarmonicTransfer(null);setTransferSelection([]);}}>Cerrar revisión</button></div><small>Firma: {harmonicTransfer.constellationSignature}</small></>}</FHSurface>}
    <FHSurface className={styles.guided}><p className={styles.kicker}>RECORRIDO DE 10 MINUTOS</p><h2>Sesión guiada</h2><p>Una secuencia de escucha, observación y registro. El audio comienza únicamente después de pulsar iniciar y nunca supera 25%.</p>{guided.status==='idle'?<button className={styles.guidedStart} onClick={startGuided}>Iniciar sesión guiada (10 min)</button>:<><div className={styles.guidedProgress}><strong>{guidedStep?.name}</strong><span>{Math.ceil(guidedRemainingSeconds(guided))} s restantes</span><progress max="600" value={GUIDED_CYMATICS_STEPS.slice(0,guided.stepIndex).reduce((sum,step)=>sum+step.durationSeconds,0)+guided.elapsedInStep}/></div>{guidedStep?.id==='preparation'&&<p>Siéntate, pantalla a la altura de los ojos.</p>}{guidedStep?.id==='sweep'&&<div className={reducedMotion?styles.breathStatic:styles.breathRing} aria-label="Guía de respiración"><span>Inhala 4 s<br/>Exhala 6 s</span></div>}{guidedJournalOpen&&<div role="region" aria-label="Registro de práctica"><h3>Registro de práctica</h3><p>{guidedPng?'La captura PNG está lista.':'La sesión quedó lista para registrar.'} Completa el diario al finalizar.</p></div>}<div className={styles.guidedActions}><button onClick={()=>setGuided(state=>state.status==='paused'?resumeGuidedCymaticsSession(state):pauseGuidedCymaticsSession(state))}>{guided.status==='paused'?'Continuar':'Pausar'}</button><button disabled={guided.status==='complete'} onClick={()=>setGuided(skipGuidedCymaticsStep)}>Saltar paso</button><button onClick={stopAll}>Terminar</button></div></>}</FHSurface>
    <section className={styles.exampleCards} aria-labelledby="figures-title"><div className={styles.exampleHeading}><p className={styles.kicker}>TRES FIGURAS CALCULADAS</p><h2 id="figures-title">Elige una resonancia para comenzar</h2></div><div className={styles.exampleGrid}>{examples.map(example=>{const field=computeModalField(example.config,example.frequencyHz,40);return <article key={example.id}><CymaticsCanvas config={{...example.config,view:'field'}} field={field} label={`Vista previa ${example.title}`} scaleMax={field.maxAmplitude}/><h3>{example.title}</h3><p>{example.modeLabel} · <strong>{example.frequencyHz.toFixed(2)} Hz</strong></p><button onClick={()=>void listenExample(example.id)}>Escuchar</button></article>;})}</div></section>
    <details className={styles.deep} open={disclosure.advanced} onToggle={event=>setDisclosureOpen('advanced',event.currentTarget.open)}><summary>Explorar a fondo</summary>
    <FHSurface className={styles.modeExplorer}><div className={styles.modeHeading}><div><p className={styles.kicker}>MEMBRANA CIRCULAR IDEAL</p><h2>Explorador de modos propios</h2><p>Elige una geometría calculada. El orden angular <strong>m</strong> indica diámetros nodales; para m mayor que cero aparecen <strong>2m sectores alternantes</strong>. El orden radial <strong>n</strong> empieza en 1 y deja <strong>n − 1 círculos nodales interiores</strong>.</p></div><div className={styles.modeTabs} role="group" aria-label="Tipo de vista modal"><button aria-pressed={modeView==='ideal'} onClick={()=>setModeView('ideal')}>Modo ideal</button><button aria-pressed={modeView==='forced'} onClick={applyIdealToForced}>Respuesta forzada</button></div></div>
      <div className={styles.modeLayout}><div className={styles.modeCanvas}><CymaticsCanvas config={modeView==='ideal'?idealConfig:config} field={modeView==='ideal'?idealField:fields[0]} label={modeView==='ideal'?`Modo ideal (${modeM}, ${modeN})`:'Respuesta forzada'} showContours exactNodes={modeView==='ideal'} animateVibration={modeView==='ideal'&&animateMode}/><div className={styles.phaseLegend}><span><i className={styles.phasePositive}/> Fase positiva</span><span><i className={styles.phaseNegative}/> Fase opuesta</span><span><i className={styles.phaseNode}/> Desplazamiento cero</span></div></div>
        <div className={styles.modeControls}><label>Orden angular m <select aria-label="Orden angular m" value={modeM} onChange={e=>setModeM(Number(e.target.value))}>{[0,1,2,3,4].map(value=><option key={value} value={value}>{value}</option>)}</select></label><p>{modeM} {modeM===1?'diámetro nodal':'diámetros nodales'} · {modeM===0?1:2*modeM} {modeM===0?'región axial':'sectores alternantes'}.</p><label>Orden radial n <select aria-label="Orden radial n" value={modeN} onChange={e=>setModeN(Number(e.target.value))}>{[1,2,3,4,5].map(value=><option key={value} value={value}>{value}</option>)}</select></label><p>{modeN-1} {modeN-1===1?'círculo nodal interior':'círculos nodales interiores'}.</p><label>Orientación {modeRotation}° <input aria-label="Orientación del modo" type="range" min="0" max="180" step="1" value={modeRotation} onInput={e=>setModeRotation(Number(e.currentTarget.value))}/></label><p>La rotación cambia la orientación visual, no la frecuencia.</p>{modeView==='ideal'?<><label><input type="checkbox" checked={animateMode} onChange={e=>setAnimateMode(e.target.checked)}/> Animación ralentizada</label><button onClick={applyIdealToForced}>Explorar como respuesta forzada</button></>:<><label>Frecuencia forzada <input aria-label="Frecuencia forzada modal" type="number" min={AUDIO_MIN_HZ} max={AUDIO_MAX_HZ} step=".01" value={Number(frequency.toFixed(2))} onInput={e=>changeFrequency(Number(e.currentTarget.value))}/> Hz</label><label>Excitación X <input aria-label="Excitación modal X" type="range" min=".05" max=".95" step=".01" value={config.excitationPosition.x} onInput={e=>patch({excitationPosition:{...config.excitationPosition,x:Number(e.currentTarget.value)}})}/></label><label>Excitación Y <input aria-label="Excitación modal Y" type="range" min=".05" max=".95" step=".01" value={config.excitationPosition.y} onInput={e=>patch({excitationPosition:{...config.excitationPosition,y:Number(e.currentTarget.value)}})}/></label><label>Amortiguamiento ζ <input aria-label="Amortiguamiento modal" type="number" min=".001" max=".3" step=".001" value={config.damping} onInput={e=>{const value=Number(e.currentTarget.value);if(value>=.001&&value<=.3)patch({damping:value});}}/></label></>}<button onClick={stopAll}>Detener todo</button></div></div>
      <div className={styles.modeFacts}><p><strong>Modo ({modeM}, {modeN}) · {idealFrequency.toFixed(2)} Hz</strong></p><p>α<sub>{modeM},{modeN}</sub> = {BESSEL_ROOTS[modeM][modeN-1].toFixed(6)} · R = {idealConfig.dimensionsSI.radiusM.toFixed(3)} m · T = {idealConfig.materialSI.tensionNm.toFixed(1)} N/m · μ = {idealConfig.materialSI.surfaceDensityKgM2.toFixed(3)} kg/m²</p><p>f<sub>mn</sub> = α<sub>mn</sub> / (2πR) × √(T/μ). Membrana homogénea ideal con borde fijo.</p><p>{modeView==='ideal'?'Las líneas claras son nodos exactos del modo ideal; los colores distinguen regiones que vibran en fases opuestas. La animación, cuando se activa, está ralentizada.':'La respuesta forzada suma varios modos. Excitar sobre un nodo puede impedir que el modo seleccionado destaque; sus contornos de amplitud mínima no siempre son nodos exactos.'}</p></div>
    </FHSurface>
    <FHSurface variant="subtle"><strong>Simulación.</strong> Modelo de membrana o placa idealizada. Las partículas son ilustrativas y esta vista no mide efectos sobre el cuerpo.</FHSurface>

    <div className={styles.workspaceIntro}><p className={styles.kicker}>RESPUESTA FORZADA · SUPERFICIE CONFIGURABLE</p><h2>{config.surfaceType==='square-plate'?'Experimento de placa':'Experimento de membrana'}</h2><p>Este espacio es independiente de la vista de modo ideal. Comienza con la placa de los ejemplos históricos; “Explorar como respuesta forzada” transfiere explícitamente el modo de membrana, su frecuencia y sus parámetros sin iniciar audio.</p></div>

    <div className={styles.toolbar}><label>Frecuencia <input aria-label="Frecuencia cimática" type="number" min={AUDIO_MIN_HZ} max={AUDIO_MAX_HZ} step=".1" value={Number(frequency.toFixed(2))} onInput={e=>changeFrequency(Number(e.currentTarget.value))}/> Hz</label><input aria-label="Deslizador de frecuencia cimática" type="range" min="0.1" max="2000" step=".1" value={frequency} onInput={e=>changeFrequency(Number(e.currentTarget.value))}/>
      <label>Superficie <select value={config.surfaceType} onChange={e=>selectSurface(e.target.value as CymaticsConfigV1['surfaceType'])}><option value="square-plate">Placa cuadrada</option><option value="circular-membrane">Membrana circular</option></select></label>
      <label>Vista <select value={config.view} onChange={e=>patch({view:e.target.value as CymaticsConfigV1['view']})}><option value="particles">Partículas ilustrativas</option><option value="vibration">Vibración ilustrativa en vivo</option><option value="field">Campo de amplitud</option><option value="nodal-lines">Contornos de amplitud mínima</option></select></label>
      <button onClick={toggleAudio}>{playing?'Detener sonido':'Escuchar tono'}</button><button onClick={()=>setHidden(v=>!v)}>{hidden?'Mostrar visual':'Ocultar visual'}</button>
    </div>
    <FHSurface variant="subtle"><h2>Exploración en vivo</h2><p>Mueve el control fino y observa cómo cambian la superficie, los contornos y la organización de partículas. Selecciona “Vibración ilustrativa en vivo” para ver la fase calculada ralentizada. Si el sonido está activo, seguirá la frecuencia; este control no inicia audio.</p><label>Alrededor de {liveCenter.toFixed(1)} Hz <input aria-label="Exploración fina de frecuencia" type="range" min={liveMin} max={liveMax} step=".05" value={Math.max(liveMin,Math.min(liveMax,frequency))} onInput={e=>changeFrequency(Number(e.currentTarget.value))}/></label><output aria-live="polite">Frecuencia actual: <strong>{frequency.toFixed(2)} Hz</strong> · distancia al modo: {detuningPercent>=0?'+':''}{detuningPercent.toFixed(2)}%</output><p><small>La fase visual está ralentizada para ser observable; no representa la velocidad física real de vibración.</small></p></FHSurface>
    {config.waveform!=='sine'&&<p role="alert">El audio usa {config.waveform}; el modelo visual MVP representa únicamente su componente fundamental y no los armónicos.</p>}
    <div className={config.audioMode==='binaural'?styles.channels:undefined}>{fields.map((field,i)=>{const channel=config.audioMode==='binaural'?(i?'Canal derecho':'Canal izquierdo'):'Respuesta simulada',proximity=Math.max(.08,1-Math.abs(config.channelFrequenciesHz[i]/field.nearestResonanceHz-1)*8);return <section key={i} className={styles.visualPanel}><h2>{channel} · {config.channelFrequenciesHz[i].toFixed(2)} Hz</h2><p>{surfaceLabel(config.surfaceType)} · {config.view==='particles'?'partículas ilustrativas':config.view==='field'?'amplitud estacionaria':config.view==='vibration'?'desplazamiento complejo ralentizado':'contornos de amplitud mínima'}.</p><CymaticsCanvas config={config} field={field} label={channel} hidden={hidden} captureRef={i===0?canvas:undefined} showContours={showContours} resetToken={resetToken} scaleMax={referenceScales[i]} interactive={i===0} force={config.excitationRelativeStrength*proximity} onFrequencyChange={changeFrequency} onExcitationChange={position=>patch({excitationPosition:position})}/><p className={styles.status} role="status">{statusText[field.status]} Resonancia más cercana: {field.nearestResonanceHz.toFixed(2)} Hz. Rango modal: {field.modeledMinHz.toFixed(2)}–{field.modeledMaxHz.toFixed(2)} Hz. {field.status!=='resonant'&&<button onClick={exploreNearest}>Explorar resonancia cercana</button>}</p></section>;})}</div>
    <ResponseChart config={config} currentHz={frequency} onSelect={changeFrequency}/>
    <ModeMap config={config} currentHz={frequency} onSelect={changeFrequency}/>
    <FHSurface><h2>Experimento guiado de placa · Encuentra una resonancia</h2><ol><li>Prepara la placa conocida y deja el audio apagado.</li><li>Inicia el barrido visual o pulsa la gráfica. Busca el máximo de amplitud RMS relativa.</li><li>Observa las regiones que vibran y los contornos de amplitud mínima; en respuesta forzada no todos son nodos exactos.</li><li>Compara el pico con una frecuencia alejada manteniendo iguales superficie, material, excitación, amortiguamiento y escala.</li></ol><div className={styles.inline}><button onClick={prepareGuide}>Preparar experimento de placa</button><button onClick={comparePeak}>Comparar pico y frecuencia alejada</button></div><p>El modo propio es una propiedad calculada de la superficie. La respuesta forzada depende además de la excitación y el amortiguamiento. Las partículas solo ilustran la organización hacia amplitudes bajas.</p></FHSurface>
    <FHSurface><h2>Demostración de resonancia</h2><p>Elige uno de tres modos propios calculados. La acción ajusta superficie, frecuencia y punto de excitación para revelar estructura interior; no inicia audio ni cambia el volumen.</p><div className={styles.inline}><label>Figura <select aria-label="Ejemplo de resonancia" value={exampleId} onChange={e=>setExampleId(e.target.value)}>{examples.map(example=><option key={example.id} value={example.id}>{example.title} · {example.modeLabel} · {example.frequencyHz.toFixed(1)} Hz</option>)}</select></label><button onClick={applyExample}>Ver figura de resonancia</button></div>{activeExample&&<p role="status"><strong>{examples.find(row=>row.id===activeExample)?.title}</strong> · {surfaceLabel(config.surfaceType)} · {examples.find(row=>row.id===activeExample)?.modeLabel} · {frequency.toFixed(1)} Hz.</p>}<p><small>Las partículas usan una animación ilustrativa con asentamiento objetivo de 3–5 segundos; no representa tiempo físico medido.</small></p></FHSurface>
    <div className={styles.grid}>
      <FHSurface><h2>Audio y fuerza virtual</h2><label>Volumen de escucha {Math.round(volume*100)}% <input aria-label="Volumen cimático" type="range" min="0" max=".6" step=".01" value={volume} onInput={e=>{const v=Number(e.currentTarget.value);setVolume(v);if(playing)setCymaticsVolume(v);}}/></label><label>Fuerza relativa {config.excitationRelativeStrength.toFixed(1)} <input type="range" min=".1" max="3" step=".1" value={config.excitationRelativeStrength} onInput={e=>patch({excitationRelativeStrength:Number(e.currentTarget.value)})}/></label><p>Son escalas independientes: el volumen digital no mide fuerza mecánica ni presión acústica.</p><h3>Usa tu voz</h3><p>El audio del micrófono se analiza en tu dispositivo y no se graba ni se guarda. No inicia el generador de tonos.</p>{microphone==='active'?<><p role="status">Micrófono activo{detectedHz?` · ${detectedHz.toFixed(2)} Hz`:''}</p><button onClick={stopMicrophone}>Detener micrófono</button></>:<button disabled={microphone==='requesting'} onClick={()=>void startMicrophone()}>{microphone==='requesting'?'Solicitando permiso…':'Activar micrófono'}</button>}<label><input type="checkbox" checked={config.audioMode==='binaural'} onChange={e=>toggleBinaural(e.target.checked)}/> Vista binaural independiente</label>{config.audioMode==='binaural'&&<label>Canal derecho <input aria-label="Frecuencia del canal derecho" type="number" min=".1" max="2000" value={config.channelFrequenciesHz[1]} onInput={e=>changeRightFrequency(Number(e.currentTarget.value))}/> Hz <small>Diferencia: {(config.channelFrequenciesHz[1]-frequency).toFixed(1)} Hz; no es un tono emitido.</small></label>}</FHSurface>
      <FHSurface><h2>Barrido visual</h2><div className={styles.inline}><label>Inicio <input aria-label="Inicio del barrido" type="number" value={sweep.start} onChange={e=>setSweep(s=>({...s,start:Number(e.target.value)}))}/></label><label>Fin <input aria-label="Fin del barrido" type="number" value={sweep.end} onChange={e=>setSweep(s=>({...s,end:Number(e.target.value)}))}/></label><label>Segundos <input aria-label="Duración del barrido" type="number" min="5" value={sweep.duration} onChange={e=>setSweep(s=>({...s,duration:Number(e.target.value)}))}/></label></div><label><input type="checkbox" checked={sweep.logarithmic} onChange={e=>setSweep(s=>({...s,logarithmic:e.target.checked}))}/> Logarítmico</label><p>El barrido cambia la simulación sin iniciar sonido. Usa “Escuchar tono” por separado si deseas audio. “Detener todo” permanece visible junto al explorador principal.</p><div className={styles.inline}><button disabled={sweep.running&&!sweep.paused} onClick={event=>runSweep(event.timeStamp)}>{sweep.paused?'Continuar barrido':'Iniciar barrido visual'}</button><button disabled={!sweep.running||sweep.paused} onClick={pauseSweep}>Pausar barrido</button><button disabled={!sweep.running} onClick={stopSweep}>Cancelar barrido</button></div></FHSurface>
      <FHSurface><h2>Comparación A/B</h2><p>Captura A y B manualmente o usa el modo “solo frecuencia”. Las frecuencias visibles se redondean a dos decimales; el cálculo conserva toda su precisión.</p><div className={styles.inline}><button onClick={()=>setA(clone(config))}>Capturar A</button><button onClick={()=>setB(clone(config))}>Capturar B</button><button onClick={comparePeak}>Preparar A/B solo frecuencia</button><button disabled={!a||!b} onClick={()=>setCompare(v=>!v)}>{compare?'Cerrar comparación':'Comparar'}</button></div>{compare&&a&&b&&<Comparison a={a} b={b}/>}</FHSurface>
      <FHSurface><h2>Configuración avanzada</h2><details><summary>Superficie, excitación y visual</summary><label>Amortiguamiento ζ <input aria-label="Amortiguamiento cimático" type="number" min=".001" max=".3" step=".001" value={config.damping} onInput={e=>{const value=Number(e.currentTarget.value);if(Number.isFinite(value)&&value>=.001&&value<=.3)patch({damping:value});else setMessage('El amortiguamiento debe estar entre 0.001 y 0.3.');}}/></label><label>Excitación X <input type="range" min=".05" max=".95" step=".01" value={config.excitationPosition.x} onInput={e=>patch({excitationPosition:{...config.excitationPosition,x:Number(e.currentTarget.value)}})}/></label><label>Excitación Y <input type="range" min=".05" max=".95" step=".01" value={config.excitationPosition.y} onInput={e=>patch({excitationPosition:{...config.excitationPosition,y:Number(e.currentTarget.value)}})}/></label><label>Calidad <select value={config.renderQuality} onChange={e=>patch({renderQuality:e.target.value as CymaticsConfigV1['renderQuality']})}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option></select></label><label><input type="checkbox" checked={showContours} onChange={e=>setShowContours(e.target.checked)}/> Superponer contornos de amplitud mínima</label><button type="button" onClick={()=>setResetToken(value=>value+1)}>Reiniciar partículas con la misma semilla</button><label><input type="checkbox" checked={config.autoExposure} onChange={e=>patch({autoExposure:e.target.checked,visualScale:e.target.checked?'auto':'fixed'})}/> Autoexposición visible</label><p>{surfaceLabel(config.surfaceType)}. Expansión modal truncada a {config.modeCutoff}. Envolvente RMS estacionaria. Los contornos indican amplitud mínima en la respuesta compleja; no siempre son nodos exactos.</p></details></FHSurface>
      <FHSurface><h2>Guardar y exportar</h2><label>Título <input value={config.title} maxLength={100} onChange={e=>patch({title:e.target.value})}/></label><label>Calma ({calm}/10) <input aria-label="Calma" type="range" min="1" max="10" step="1" value={calm} onInput={e=>setCalm(Number(e.currentTarget.value))}/></label><label>Nota <textarea aria-label="Nota" maxLength={280} value={journalNote} onChange={e=>setJournalNote(e.target.value)}/><small>{journalNote.length}/280</small></label><div className={styles.inline}><button onClick={save}>Guardar figura</button><button onClick={exportPNG}>Capturar PNG</button><button onClick={()=>exportJSON()}>Exportar JSON</button><button onClick={exportJournalCsv}>Exportar diario CSV</button><label className={styles.file}>Importar JSON<input type="file" accept="application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{setConfig(parseCymaticsImport(await file.text()));setMessage('Configuración importada y validada.');}catch(err){setMessage((err as Error).message);}}}/></label></div>{message&&<p role="status">{message}</p>}<h3>Galería local ({gallery.length})</h3><ul>{gallery.map(row=><li key={row.id}><button onClick={()=>setConfig(clone(row))}>{new Date(row.createdAt).toLocaleDateString('es-MX')} · {row.title} · {row.channelFrequenciesHz.join('/')} Hz{row.journal?` · calma ${row.journal.calm}/10 · ${row.journal.note.split('\n')[0]}`:''} · cargar</button> <button onClick={()=>exportJSON(row)}>JSON</button></li>)}</ul><h3>Últimos 30 días</h3><ul>{gallery.filter(row=>row.journal&&Date.parse(row.journal.createdAt)>=JOURNAL_30_DAY_CUTOFF).sort((x,y)=>Date.parse(y.journal!.createdAt)-Date.parse(x.journal!.createdAt)).map(row=><li key={`journal-${row.id}`}>{new Date(row.journal!.createdAt).toLocaleDateString('es-MX')} · calma {row.journal!.calm}/10</li>)}</ul></FHSurface>
    </div></details>
    <details className={styles.how} open={disclosure.how} onToggle={event=>setDisclosureOpen('how',event.currentTarget.open)}><summary>Cómo funciona</summary><p>El campo suma primero respuestas modales complejas y después calcula su magnitud: qⱼ(ω)=Fⱼ/[mⱼ(ωⱼ²−ω²+i·2ζωⱼω)]. La placa isotrópica delgada usa D=Eh³/[12(1−ν²)] y bordes simplemente apoyados. La membrana usa raíces de Bessel Jₘ y borde fijo. La expansión se trunca a {config.modeCutoff} modos por índice; ζ={config.damping.toFixed(3)} mantiene finita la respuesta.</p><p>Dimensiones: placa {config.dimensionsSI.widthM}×{config.dimensionsSI.heightM} m, espesor {config.dimensionsSI.thicknessM} m; membrana radio {config.dimensionsSI.radiusM} m. Material: E={config.materialSI.youngModulusPa.toExponential(2)} Pa, ν={config.materialSI.poissonRatio}, densidad={config.materialSI.densityKgM3} kg/m³, tensión={config.materialSI.tensionNm} N/m y densidad superficial={config.materialSI.surfaceDensityKgM2} kg/m².</p><p>Modo propio, respuesta forzada y partículas ilustrativas son conceptos distintos. Los contornos muestran amplitud mínima de la respuesta compleja y no se presentan automáticamente como nodos exactos. El modelo ideal no mide efectos corporales ni demuestra efectos terapéuticos.</p></details>
  </FHPageShell>;
}
function ResponseChart({config,currentHz,onSelect}:{config:CymaticsConfigV1;currentHz:number;onSelect:(hz:number)=>void}){const mode=nearestMode(config,currentHz),start=Math.max(AUDIO_MIN_HZ,mode.frequencyHz*.78),end=Math.min(AUDIO_MAX_HZ,mode.frequencyHz*1.22),curve=computeResponseCurve(config,start,end,101),peak=curve.reduce((best,row)=>row.rmsAmplitude>best.rmsAmplitude?row:best),max=Math.max(...curve.map(row=>row.rmsAmplitude),1e-20),w=760,h=250,pad=36,points=curve.map(row=>`${pad+(row.frequencyHz-start)/(end-start)*(w-pad*2)},${h-pad-row.rmsAmplitude/max*(h-pad*2)}`).join(' '),currentX=pad+(currentHz-start)/(end-start)*(w-pad*2),peakX=pad+(peak.frequencyHz-start)/(end-start)*(w-pad*2);const select=(clientX:number,target:SVGSVGElement)=>{const rect=target.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(clientX-rect.left)/rect.width));onSelect(start+ratio*(end-start));};return <FHSurface><h2>Respuesta frente a frecuencia</h2><p>Magnitud: amplitud RMS relativa del modelo (u.r.). La escala vertical permanece común en este rango; no usa autoexposición. Pulsa o usa las acciones bajo la gráfica para cambiar la frecuencia sin iniciar audio.</p><svg className={styles.chart} viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Curva de amplitud RMS relativa frente a frecuencia" tabIndex={0} onPointerDown={e=>select(e.clientX,e.currentTarget)} onKeyDown={e=>{if(e.key==='ArrowLeft')onSelect(Math.max(start,currentHz-(end-start)/100));if(e.key==='ArrowRight')onSelect(Math.min(end,currentHz+(end-start)/100));}}><line x1={pad} y1={h-pad} x2={w-pad} y2={h-pad}/><line x1={pad} y1={pad} x2={pad} y2={h-pad}/><polyline points={points}/><line className={styles.current} x1={currentX} y1={pad} x2={currentX} y2={h-pad}/><circle className={styles.peak} cx={peakX} cy={h-pad-peak.rmsAmplitude/max*(h-pad*2)} r="6"/><text x={pad} y={h-10}>{start.toFixed(2)} Hz</text><text x={w-pad-70} y={h-10}>{end.toFixed(2)} Hz</text></svg><div className={styles.inline}><button onClick={()=>onSelect(peak.frequencyHz)}>Ir al pico {peak.frequencyHz.toFixed(2)} Hz</button><button onClick={()=>onSelect(start)}>Ir al extremo {start.toFixed(2)} Hz</button></div><p>Actual: <strong>{currentHz.toFixed(2)} Hz</strong> · pico muestreado: <strong>{peak.frequencyHz.toFixed(2)} Hz</strong> · rango modal calculado: {buildModes(config)[0].frequencyHz.toFixed(2)}–{buildModes(config).at(-1)!.frequencyHz.toFixed(2)} Hz.</p></FHSurface>}

function Comparison({a,b}:{a:CymaticsConfigV1;b:CymaticsConfigV1}){const fa=computeModalField(a,a.channelFrequenciesHz[0]),fb=computeModalField(b,b.channelFrequenciesHz[0]),scale=Math.max(fa.maxAmplitude,fb.maxAmplitude)*2,samePhysics=JSON.stringify({...a,id:'',createdAt:'',title:'',channelFrequenciesHz:[],modeledComponents:[]})===JSON.stringify({...b,id:'',createdAt:'',title:'',channelFrequenciesHz:[],modeledComponents:[]});return <div><table className={styles.compareTable}><caption>Parámetros que difieren</caption><thead><tr><th>Parámetro</th><th>Captura A</th><th>Captura B</th></tr></thead><tbody><tr><th>Frecuencia</th><td>{a.channelFrequenciesHz.map(v=>v.toFixed(2)).join(' / ')} Hz</td><td>{b.channelFrequenciesHz.map(v=>v.toFixed(2)).join(' / ')} Hz</td></tr>{a.surfaceType!==b.surfaceType&&<tr><th>Superficie</th><td>{surfaceLabel(a.surfaceType)}</td><td>{surfaceLabel(b.surfaceType)}</td></tr>}{a.damping!==b.damping&&<tr><th>Amortiguamiento</th><td>{a.damping}</td><td>{b.damping}</td></tr>}</tbody></table><p>{samePhysics?'Solo cambia la frecuencia; condiciones físicas y escala visual comunes.':'Hay otras diferencias además de la frecuencia; revisa la tabla y las capturas antes de interpretar.'}</p><div className={styles.channels}><section><h3>Captura A · {a.channelFrequenciesHz[0].toFixed(2)} Hz</h3><CymaticsCanvas config={a} field={fa} label="Comparación A" scaleMax={scale}/></section><section><h3>Captura B · {b.channelFrequenciesHz[0].toFixed(2)} Hz</h3><CymaticsCanvas config={b} field={fb} label="Comparación B" scaleMax={scale}/></section></div></div>}

/** Static miniature of the forced response at one resonance: amplitude field, bright where the plate moves and dark in low-amplitude regions. */
function ModeThumb({config,frequencyHz}:{config:CymaticsConfigV1;frequencyHz:number}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;const field=computeModalField(config,frequencyHz,40),size=field.size,image=ctx.createImageData(size,size),max=Math.max(field.maxAmplitude,1e-20),circular=config.surfaceType==='circular-membrane';for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=y*size+x,o=i*4,outside=circular&&Math.hypot((x+.5)/size-.5,(y+.5)/size-.5)>.5,t=outside?0:Math.min(1,field.values[i]/max);image.data[o]=outside?3:Math.round(14+226*t*t);image.data[o+1]=outside?7:Math.round(20+200*t);image.data[o+2]=outside?17:Math.round(40+170*t);image.data[o+3]=255;}canvas.width=size;canvas.height=size;ctx.putImageData(image,0,0);},[config,frequencyHz]);return <canvas ref={ref} className={styles.modeThumb} aria-hidden="true"/>;}

/** Map of every driven resonance with its figure, so frequency → figure can be read at a glance. Selecting one tunes the plate without starting audio. */
function ModeMap({config,currentHz,onSelect}:{config:CymaticsConfigV1;currentHz:number;onSelect:(hz:number)=>void}){
  // The map depends on the surface, material and excitation, not on the current frequency.
  const physicsKey=JSON.stringify({...config,id:'',createdAt:'',title:'',channelFrequenciesHz:[],modeledComponents:[],view:'',journal:undefined});
  const {stable,entries}=useMemo(()=>{const parsed=JSON.parse(physicsKey) as CymaticsConfigV1;return {stable:parsed,entries:buildModeMap(parsed)};},[physicsKey]);
  const active=entries.reduce<number|null>((best,entry,index)=>best===null||Math.abs(entry.frequencyHz-currentHz)<Math.abs(entries[best].frequencyHz-currentHz)?index:best,null);
  return <FHSurface><p className={styles.kicker}>MAPA DE MODOS</p><h2>Cada resonancia y su figura</h2><p>Cada pico de la respuesta se asocia con uno o más modos propios de esta superficie. Pulsa uno para afinar la placa a esa frecuencia (no inicia audio). Solo aparecen los modos que el punto de excitación actual activa de forma apreciable; si mueves la excitación, el mapa cambia. Zonas claras: mayor amplitud calculada. Zonas oscuras: regiones de amplitud mínima, donde las partículas ilustrativas tienden a acumularse.</p>
    <ol className={styles.modeMap}>{entries.map((entry,index)=>{const isActive=index===active&&Math.abs(entry.frequencyHz/currentHz-1)<.02;return <li key={entry.modeIds.join('+')}><button aria-pressed={isActive} aria-label={`Afinar a ${entry.labels.join(' y ')}, ${entry.frequencyHz.toFixed(2)} Hz`} onClick={()=>onSelect(entry.frequencyHz)}><ModeThumb config={stable} frequencyHz={entry.frequencyHz}/><strong>{entry.frequencyHz.toFixed(2)} Hz</strong><span>{entry.labels[0]}{entry.labels.length>1?` +${entry.labels.length-1}`:''}</span></button></li>;})}</ol>
    {!entries.length&&<p>No hay modos excitados en el rango de audio con esta configuración.</p>}
  </FHSurface>;
}
