import { FrequencyEntry } from './types';

/**
 * Base de datos completa de frecuencias para sanación.
 * Fuentes: Estudio Rife (PDF), Frecuencias Solfeggio, CAFL, MIT Research
 */
export const FREQUENCY_DATABASE: FrequencyEntry[] = [
  // ─── ONDAS CEREBRALES / NEUROESTIMULACIÓN ──────────────────────
  {
    id: 'bw-epsilon',
    hz: 0.5,
    name: 'Epsilon',
    description: 'Meditación profunda extraordinaria. Estado de consciencia expandida.',
    category: 'brainwave',
    domain: ['espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['meditacion', 'consciencia', 'epsilon'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-delta-low',
    hz: 1,
    name: 'Delta Profundo',
    description: 'Sueño profundo sin sueños. Regeneración celular máxima.',
    category: 'brainwave',
    domain: ['cuerpo'],
    evidence: 'verificada',
    waveformRecommended: 'sine',
    tags: ['sueño', 'regeneracion', 'delta'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-delta',
    hz: 2,
    name: 'Delta',
    description: 'Sueño reparador. Liberación de hormona de crecimiento.',
    category: 'brainwave',
    domain: ['cuerpo'],
    evidence: 'verificada',
    waveformRecommended: 'sine',
    tags: ['sueño', 'regeneracion', 'delta', 'crecimiento'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-theta-low',
    hz: 4,
    name: 'Theta Bajo',
    description: 'Frontera sueño-vigilia. Acceso al subconsciente.',
    category: 'brainwave',
    domain: ['alma', 'espiritu'],
    evidence: 'verificada',
    waveformRecommended: 'sine',
    tags: ['meditacion', 'subconsciente', 'theta'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-theta',
    hz: 6,
    name: 'Theta',
    description: 'Meditación profunda. Creatividad, insight y sanación emocional.',
    category: 'brainwave',
    domain: ['alma', 'espiritu'],
    evidence: 'verificada',
    waveformRecommended: 'sine',
    tags: ['meditacion', 'creatividad', 'theta', 'insight'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-schumann',
    hz: 7.83,
    name: 'Resonancia Schumann',
    description: 'Frecuencia natural de la Tierra. Equilibrio y conexión con el planeta.',
    category: 'brainwave',
    domain: ['cuerpo', 'alma', 'espiritu'],
    evidence: 'verificada',
    waveformRecommended: 'sine',
    tags: ['tierra', 'equilibrio', 'schumann', 'resonancia'],
    source: 'Geofísica',
  },
  {
    id: 'bw-alpha-low',
    hz: 8,
    name: 'Alpha Bajo',
    description: 'Relajación ligera. Puente entre consciente y subconsciente.',
    category: 'brainwave',
    domain: ['alma'],
    evidence: 'verificada',
    waveformRecommended: 'sine',
    tags: ['relajacion', 'alpha', 'calma'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-alpha',
    hz: 10,
    name: 'Alpha Central',
    description: 'Relajación óptima. Concentración serena, flujo creativo.',
    category: 'brainwave',
    domain: ['alma'],
    evidence: 'verificada',
    waveformRecommended: 'sine',
    tags: ['relajacion', 'concentracion', 'alpha', 'flujo'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-alpha-high',
    hz: 12,
    name: 'Alpha Alto',
    description: 'Alerta relajada. Estado ideal para aprendizaje.',
    category: 'brainwave',
    domain: ['alma'],
    evidence: 'verificada',
    waveformRecommended: 'sine',
    tags: ['aprendizaje', 'alpha', 'alerta'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-beta',
    hz: 20,
    name: 'Beta',
    description: 'Concentración activa. Pensamiento lógico y analítico.',
    category: 'brainwave',
    domain: ['alma'],
    evidence: 'verificada',
    waveformRecommended: 'sine',
    tags: ['concentracion', 'beta', 'logica'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-gamma',
    hz: 40,
    name: 'Gamma - Neuroprotección',
    description: 'Investigación MIT: reduce placas amiloides en Alzheimer. Rendimiento cognitivo máximo.',
    category: 'brainwave',
    domain: ['cuerpo', 'alma'],
    evidence: 'verificada',
    waveformRecommended: 'sine',
    tags: ['gamma', 'alzheimer', 'neuroproteccion', 'cognitivo', 'MIT'],
    source: 'MIT Research',
  },
  {
    id: 'bw-gamma-high',
    hz: 100,
    name: 'Gamma Alto',
    description: 'Hiperconcentración. Estados pico de consciencia.',
    category: 'brainwave',
    domain: ['espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['gamma', 'consciencia', 'pico'],
    source: 'Neuroestimulación',
  },

  // ─── SOLFEGGIO ─────────────────────────────────────────────────
  {
    id: 'sol-174',
    hz: 174,
    name: 'Fundación',
    description: 'Alivio del dolor. Reduce tensión física y emocional. Base de la escala Solfeggio.',
    category: 'solfeggio',
    domain: ['cuerpo'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['dolor', 'tension', 'fundacion', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-285',
    hz: 285,
    name: 'Sanación Celular',
    description: 'Restauración celular y tisular. Activa campo energético de regeneración.',
    category: 'solfeggio',
    domain: ['cuerpo'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['celular', 'restauracion', 'regeneracion', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-396',
    hz: 396,
    name: 'Liberación',
    description: 'Liberar miedo y culpa. Desbloquea patrones emocionales atrapados.',
    category: 'solfeggio',
    domain: ['alma'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['miedo', 'culpa', 'liberacion', 'emocional', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-417',
    hz: 417,
    name: 'Facilitador del Cambio',
    description: 'Facilita cambio y transformación. Deshace situaciones negativas.',
    category: 'solfeggio',
    domain: ['alma'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['cambio', 'transformacion', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-528',
    hz: 528,
    name: 'Frecuencia del Milagro',
    description: 'Reparación del ADN. Transformación y milagros. La frecuencia del amor.',
    category: 'solfeggio',
    domain: ['cuerpo', 'alma', 'espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['adn', 'milagro', 'amor', 'transformacion', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-639',
    hz: 639,
    name: 'Conexión',
    description: 'Armonía en relaciones. Reconecta con otros y contigo mismo.',
    category: 'solfeggio',
    domain: ['alma'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['relaciones', 'armonia', 'conexion', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-741',
    hz: 741,
    name: 'Expresión',
    description: 'Claridad mental. Despertar intuición. Limpieza de toxinas.',
    category: 'solfeggio',
    domain: ['alma', 'espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['claridad', 'intuicion', 'expresion', 'toxinas', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-852',
    hz: 852,
    name: 'Intuición',
    description: 'Retorno al orden espiritual. Despertar del tercer ojo.',
    category: 'solfeggio',
    domain: ['espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['intuicion', 'espiritual', 'tercer-ojo', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-963',
    hz: 963,
    name: 'Corona Divina',
    description: 'Conexión con la fuente divina. Activación de la glándula pineal.',
    category: 'solfeggio',
    domain: ['espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['corona', 'divino', 'pineal', 'consciencia', 'solfeggio'],
    source: 'Solfeggio',
  },

  // ─── AFINACIÓN MUSICAL ────────────────────────────────────────
  {
    id: 'mus-432',
    hz: 432,
    name: 'Afinación Natural',
    description: 'Afinación de las catedrales antiguas. Reduce ritmo cardíaco. Armonía natural.',
    category: 'musical',
    domain: ['cuerpo', 'alma'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['432', 'natural', 'catedrales', 'armonia', 'cardiaco'],
    source: 'Afinación Musical',
  },

  // ─── FRECUENCIAS RIFE / CAFL ──────────────────────────────────
  {
    id: 'rife-72',
    hz: 72,
    name: 'Equilibrio Emocional',
    description: 'Frecuencia de sanación emocional. Estabiliza el campo energético.',
    category: 'rife',
    domain: ['alma'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['emocional', 'equilibrio', 'rife'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-306',
    hz: 306,
    name: 'Lyme',
    description: 'Frecuencia CAFL para enfermedad de Lyme (Borrelia burgdorferi).',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['lyme', 'borrelia', 'bacterias', 'rife', 'CAFL'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-727',
    hz: 727,
    name: 'Antibacteriano General',
    description: 'Frecuencia Rife general para bacterias y heridas. Una de las más usadas.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['bacterias', 'heridas', 'rife', 'antibacteriano'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-787',
    hz: 787,
    name: 'Anti-infecciones',
    description: 'Frecuencia Rife para infecciones generales.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['infecciones', 'rife', 'patogenos'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-880',
    hz: 880,
    name: 'Antiviral / Inmunidad',
    description: 'Frecuencia Rife antiviral. Fortalece el sistema inmunológico.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['virus', 'inmunidad', 'rife', 'antiviral'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-1150',
    hz: 1150,
    name: 'Desintoxicación Parásitos',
    description: 'Frecuencia CAFL para desintoxicación parasitaria.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['parasitos', 'desintoxicacion', 'rife', 'CAFL'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-1550',
    hz: 1550,
    name: 'Inmunidad Profunda',
    description: 'Frecuencia Rife para inmunidad profunda y fortalecimiento general.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['inmunidad', 'rife', 'fortalecimiento'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-2112',
    hz: 2112,
    name: 'Antiparasitario',
    description: 'Frecuencia CAFL antiparasitaria. Uso conjunto con 993.98 Hz.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['parasitos', 'rife', 'CAFL'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-993',
    hz: 993.98,
    name: 'Antiparasitario Complementario',
    description: 'Frecuencia CAFL complementaria antiparasitaria. Usar con 2112 Hz.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['parasitos', 'rife', 'CAFL'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-5000',
    hz: 5000,
    name: 'Alergias / Senos Nasales',
    description: 'Frecuencia Rife para alergias y congestión de senos nasales.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['alergias', 'senos', 'nasal', 'rife'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-10000',
    hz: 10000,
    name: 'Alergias General',
    description: 'Frecuencia Rife general para alergias.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['alergias', 'rife'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-20000',
    hz: 20000,
    name: 'Terapéutico General',
    description: 'Frecuencia Rife terapéutica general. Límite superior audible.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['general', 'terapeutico', 'rife'],
    source: 'Rife/CAFL',
  },

  // ─── NOGIER ───────────────────────────────────────────────────
  {
    id: 'nog-292',
    hz: 292,
    name: 'Nogier A',
    description: 'Frecuencia Nogier para tejidos ectodérmicos (piel, nervios).',
    category: 'nogier',
    domain: ['cuerpo'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['nogier', 'piel', 'nervios', 'ectodermo'],
    source: 'Dr. Paul Nogier',
  },
  {
    id: 'nog-584',
    hz: 584,
    name: 'Nogier B',
    description: 'Frecuencia Nogier para tejidos endodérmicos (órganos internos).',
    category: 'nogier',
    domain: ['cuerpo'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['nogier', 'organos', 'endodermo'],
    source: 'Dr. Paul Nogier',
  },
  {
    id: 'nog-1168',
    hz: 1168,
    name: 'Nogier C',
    description: 'Frecuencia Nogier para tejidos mesodérmicos (músculos, huesos).',
    category: 'nogier',
    domain: ['cuerpo'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['nogier', 'musculos', 'huesos', 'mesodermo'],
    source: 'Dr. Paul Nogier',
  },
];

// ─── Helpers ──────────────────────────────────────────────────────

export function getFrequencyById(id: string): FrequencyEntry | undefined {
  return FREQUENCY_DATABASE.find((f) => f.id === id);
}

export function getFrequenciesByCategory(category: FrequencyEntry['category']): FrequencyEntry[] {
  return FREQUENCY_DATABASE.filter((f) => f.category === category);
}

export function getFrequenciesByDomain(domain: FrequencyEntry['domain'][number]): FrequencyEntry[] {
  return FREQUENCY_DATABASE.filter((f) => f.domain.includes(domain));
}

export function searchFrequencies(query: string): FrequencyEntry[] {
  const q = query.toLowerCase();
  return FREQUENCY_DATABASE.filter(
    (f) =>
      f.name.toLowerCase().includes(q) ||
      f.description.toLowerCase().includes(q) ||
      f.tags.some((t) => t.includes(q)) ||
      f.hz.toString().includes(q)
  );
}

export const CATEGORY_INFO: Record<FrequencyEntry['category'], { label: string; color: string; icon: string }> = {
  brainwave: { label: 'Ondas Cerebrales', color: '#a78bfa', icon: '🧠' },
  solfeggio: { label: 'Solfeggio', color: '#fbbf24', icon: '🎵' },
  rife: { label: 'Rife / CAFL', color: '#f87171', icon: '⚡' },
  musical: { label: 'Musical', color: '#4ade80', icon: '🎶' },
  nogier: { label: 'Nogier', color: '#60a5fa', icon: '🔬' },
};

export const DOMAIN_INFO: Record<string, { label: string; color: string; icon: string }> = {
  cuerpo: { label: 'Cuerpo', color: '#f87171', icon: '🫀' },
  alma: { label: 'Alma', color: '#a78bfa', icon: '🧘' },
  espiritu: { label: 'Espíritu', color: '#67e8f9', icon: '✨' },
};

export const WAVEFORM_INFO: Record<string, { label: string; icon: string }> = {
  sine: { label: 'Sinusoidal', icon: '〰️' },
  square: { label: 'Cuadrada', icon: '⊓' },
  triangle: { label: 'Triangular', icon: '△' },
  sawtooth: { label: 'Sierra', icon: '⩘' },
};
