import { FrequencyEntry } from './types';

/**
 * Catálogo histórico y exploratorio de frecuencias.
 * Las etiquetas de fuente son procedencia declarada del contenido heredado, no validación.
 */
export const FREQUENCY_DATABASE: FrequencyEntry[] = [
  // ─── ONDAS CEREBRALES / NEUROESTIMULACIÓN ──────────────────────
  {
    id: 'bw-epsilon',
    hz: 0.5,
    name: 'Epsilon',
    description: 'Tono exploratorio de 0.5 Hz asociado históricamente con prácticas meditativas. No se presupone un estado de consciencia.',
    category: 'brainwave',
    domain: ['espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['meditacion', 'consciencia', 'epsilon'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-delta-low',
    hz: 1,
    name: 'Delta Profundo',
    description: 'Tono de 1 Hz asociado de forma exploratoria con la banda delta. No se atribuye sueño ni regeneración celular.',
    category: 'brainwave',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'sine',
    tags: ['sueño', 'regeneracion', 'delta'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-delta',
    hz: 2,
    name: 'Delta',
    description: 'Tono de 2 Hz asociado de forma exploratoria con la banda delta. No se atribuyen sueño reparador ni efectos hormonales.',
    category: 'brainwave',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'sine',
    tags: ['sueño', 'regeneracion', 'delta', 'crecimiento'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-theta-low',
    hz: 4,
    name: 'Theta Bajo',
    description: 'Tono de 4 Hz descrito aquí como referencia del límite inferior theta. Las asociaciones mentales son exploratorias.',
    category: 'brainwave',
    domain: ['alma', 'espiritu'],
    evidence: 'especulativa',
    waveformRecommended: 'sine',
    tags: ['meditacion', 'subconsciente', 'theta'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-theta',
    hz: 6,
    name: 'Theta',
    description: 'Tono de 6 Hz descrito como referencia theta para exploración subjetiva. No promete creatividad ni efectos emocionales.',
    category: 'brainwave',
    domain: ['alma', 'espiritu'],
    evidence: 'especulativa',
    waveformRecommended: 'sine',
    tags: ['meditacion', 'creatividad', 'theta', 'insight'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-schumann',
    hz: 7.83,
    name: 'Resonancia Schumann',
    description: 'Valor asociado a la resonancia electromagnética Schumann. Su reproducción acústica no implica equilibrio ni conexión fisiológica.',
    category: 'brainwave',
    domain: ['cuerpo', 'alma', 'espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['tierra', 'equilibrio', 'schumann', 'resonancia'],
    source: 'Geofísica',
  },
  {
    id: 'bw-alpha-low',
    hz: 8,
    name: 'Alpha Bajo — Umbral',
    description: 'Referencia de 8 Hz al límite inferior de la banda Alpha. Esta reproducción no mide EEG ni establece efectos mentales.',
    category: 'brainwave',
    domain: ['alma'],
    evidence: 'especulativa',
    waveformRecommended: 'sine',
    tags: ['relajacion', 'alpha', 'calma', 'umbral', 'EEG'],
    source: 'Resonancia Alfa',
  },
  {
    id: 'bw-alpha',
    hz: 10,
    name: 'Alpha Central — Samadhi',
    description: 'Referencia Alpha de 10 Hz con una asociación cultural histórica a Samadhi. No se prometen tolerancia o estados mentales específicos.',
    category: 'brainwave',
    domain: ['alma', 'espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['samadhi', 'meditacion', 'alpha', 'continuo', 'india', 'yoga'],
    source: 'Resonancia Alfa',
  },
  {
    id: 'bw-alpha-iq-11',
    hz: 11,
    name: 'Alpha 11 Hz — Referencia',
    description: 'Referencia de 11 Hz dentro de la banda Alpha. No se atribuyen IQ, procesamiento acelerado ni coherencia cerebral.',
    category: 'brainwave',
    domain: ['alma'],
    evidence: 'especulativa',
    waveformRecommended: 'sine',
    tags: ['IQ', 'alpha', 'inteligencia', 'coherencia', 'procesamiento'],
    source: 'Resonancia Alfa',
  },
  {
    id: 'bw-alpha-high',
    hz: 12,
    name: 'Alpha 12 Hz — Referencia',
    description: 'Referencia de 12 Hz dentro de la banda Alpha. No representa una firma de genialidad ni promete cambios de IQ o estrés.',
    category: 'brainwave',
    domain: ['alma'],
    evidence: 'especulativa',
    waveformRecommended: 'sine',
    tags: ['IQ', 'genio', 'alpha', 'alto-rendimiento', 'coherencia', 'amplitud'],
    source: 'Resonancia Alfa',
  },
  {
    id: 'bw-alpha-peak',
    hz: 13,
    name: 'Alpha Pico — Satori',
    description: 'Referencia de 13 Hz al límite superior Alpha con una asociación cultural histórica a Satori. No se atribuyen efectos neurológicos.',
    category: 'brainwave',
    domain: ['alma', 'espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['satori', 'zen', 'alpha', 'reactivo', 'japon', 'supresion', 'pico'],
    source: 'Resonancia Alfa',
  },
  {
    id: 'bw-nfb-reward',
    hz: 600,
    name: 'Tono intercalado 600 Hz',
    description: 'Tono heredado de 600 Hz usado en una secuencia Alpha. La app no mide EEG y este tono no equivale a neurofeedback.',
    category: 'brainwave',
    domain: ['alma'],
    evidence: 'especulativa',
    waveformRecommended: 'sine',
    tags: ['neurofeedback', 'recompensa', 'sweet-spot', 'entrenamiento', 'EEG'],
    source: 'Resonancia Alfa',
  },
  {
    id: 'bw-beta',
    hz: 20,
    name: 'Beta',
    description: 'Referencia de 20 Hz asociada a la banda Beta. Cualquier respuesta subjetiva debe observarse sin asumir un efecto cognitivo.',
    category: 'brainwave',
    domain: ['alma'],
    evidence: 'especulativa',
    waveformRecommended: 'sine',
    tags: ['concentracion', 'beta', 'logica'],
    source: 'Neuroestimulación',
  },
  {
    id: 'bw-gamma',
    hz: 40,
    name: 'Gamma 40 Hz — Referencia',
    description: 'Referencia de 40 Hz asociada a la banda Gamma. El catálogo no representa evidencia clínica, neuroprotección ni tratamiento de Alzheimer.',
    category: 'brainwave',
    domain: ['cuerpo', 'alma'],
    evidence: 'especulativa',
    waveformRecommended: 'sine',
    tags: ['gamma', 'alzheimer', 'neuroproteccion', 'cognitivo', 'MIT'],
    source: 'MIT Research',
  },
  {
    id: 'bw-gamma-high',
    hz: 100,
    name: 'Gamma Alto',
    description: 'Referencia exploratoria de 100 Hz. No se atribuyen hiperconcentración ni estados de consciencia específicos.',
    category: 'brainwave',
    domain: ['espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['gamma', 'consciencia', 'pico'],
    source: 'Neuroestimulación',
  },

  // ─── SOLFEGGIO ─────────────────────────────────────────────────
  {
    id: 'sol-174',
    hz: 174,
    name: 'Fundación',
    description: 'Tono presente en repertorios Solfeggio modernos. Las asociaciones con dolor o tensión son históricas y no están validadas aquí.',
    category: 'solfeggio',
    domain: ['cuerpo'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['dolor', 'tension', 'fundacion', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-285',
    hz: 285,
    name: '285 Hz Solfeggio',
    description: 'Tono presente en repertorios Solfeggio modernos. Las asociaciones con restauración celular o campos energéticos no están validadas.',
    category: 'solfeggio',
    domain: ['cuerpo'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['celular', 'restauracion', 'regeneracion', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-396',
    hz: 396,
    name: 'Liberación',
    description: 'Tono presente en repertorios Solfeggio modernos, asociado tradicionalmente con liberación emocional. Se conserva como referencia histórica.',
    category: 'solfeggio',
    domain: ['alma'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['miedo', 'culpa', 'liberacion', 'emocional', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-417',
    hz: 417,
    name: 'Facilitador del Cambio',
    description: 'Tono presente en repertorios Solfeggio modernos, asociado tradicionalmente con cambio. No se afirma un efecto causal.',
    category: 'solfeggio',
    domain: ['alma'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['cambio', 'transformacion', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-528',
    hz: 528,
    name: '528 Hz Solfeggio',
    description: 'Tono asociado en fuentes populares con amor o reparación del ADN. Esas afirmaciones se conservan como historia no validada.',
    category: 'solfeggio',
    domain: ['cuerpo', 'alma', 'espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['adn', 'milagro', 'amor', 'transformacion', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-639',
    hz: 639,
    name: 'Conexión',
    description: 'Tono presente en repertorios Solfeggio modernos, asociado tradicionalmente con conexión. No se afirma un efecto interpersonal.',
    category: 'solfeggio',
    domain: ['alma'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['relaciones', 'armonia', 'conexion', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-741',
    hz: 741,
    name: 'Expresión',
    description: 'Tono presente en repertorios Solfeggio modernos. Las asociaciones con intuición o toxinas son tradicionales y no están validadas.',
    category: 'solfeggio',
    domain: ['alma', 'espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['claridad', 'intuicion', 'expresion', 'toxinas', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-852',
    hz: 852,
    name: 'Intuición',
    description: 'Tono asociado en tradiciones espirituales modernas con intuición o tercer ojo. Se presenta como referencia histórica, no fisiológica.',
    category: 'solfeggio',
    domain: ['espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['intuicion', 'espiritual', 'tercer-ojo', 'solfeggio'],
    source: 'Solfeggio',
  },
  {
    id: 'sol-963',
    hz: 963,
    name: '963 Hz Solfeggio',
    description: 'Tono asociado en tradiciones espirituales modernas con corona o conexión divina. No se afirma activación de la glándula pineal.',
    category: 'solfeggio',
    domain: ['espiritu'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['corona', 'divino', 'pineal', 'consciencia', 'solfeggio'],
    source: 'Solfeggio',
  },

  // ─── AFINACIÓN MUSICAL ────────────────────────────────────────
  {
    id: 'mus-432',
    hz: 432,
    name: 'Afinación 432 Hz',
    description: 'Referencia de afinación musical a 432 Hz. Las atribuciones históricas y efectos sobre ritmo cardíaco no se consideran establecidos.',
    category: 'musical',
    domain: ['cuerpo', 'alma'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['432', 'natural', 'catedrales', 'armonia', 'cardiaco'],
    source: 'Afinación Musical',
  },

  // ─── FRECUENCIAS RIFE / CAFL ──────────────────────────────────
  {
    id: 'rife-72',
    hz: 72,
    name: 'Rife/CAFL 72 Hz (histórico)',
    description: 'Valor heredado atribuido a listas Rife/CAFL. No se afirma sanación emocional ni estabilización de campos energéticos.',
    category: 'rife',
    domain: ['alma'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['emocional', 'equilibrio', 'rife'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-306',
    hz: 306,
    name: 'CAFL 306 Hz (histórico)',
    description: 'Valor heredado atribuido a listas CAFL relacionadas con Lyme. No representa diagnóstico, prevención ni tratamiento.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['lyme', 'borrelia', 'bacterias', 'rife', 'CAFL'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-727',
    hz: 727,
    name: 'Rife 727 Hz (histórico)',
    description: 'Valor heredado atribuido a listas Rife sobre bacterias o heridas. No representa evidencia antibacteriana ni tratamiento.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['bacterias', 'heridas', 'rife', 'antibacteriano'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-787',
    hz: 787,
    name: 'Rife 787 Hz (histórico)',
    description: 'Valor heredado atribuido a listas Rife sobre infecciones. No representa tratamiento ni evidencia clínica.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['infecciones', 'rife', 'patogenos'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-880',
    hz: 880,
    name: 'Rife 880 Hz (histórico)',
    description: 'Valor heredado atribuido a listas Rife sobre virus o inmunidad. No se afirman efectos antivirales o inmunológicos.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['virus', 'inmunidad', 'rife', 'antiviral'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-1150',
    hz: 1150,
    name: 'CAFL 1150 Hz (histórico)',
    description: 'Valor heredado atribuido a listas CAFL sobre parásitos. No representa desintoxicación ni tratamiento.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['parasitos', 'desintoxicacion', 'rife', 'CAFL'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-1550',
    hz: 1550,
    name: 'Rife 1550 Hz (histórico)',
    description: 'Valor heredado atribuido a listas Rife sobre inmunidad. No se afirma fortalecimiento inmunológico.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['inmunidad', 'rife', 'fortalecimiento'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-2112',
    hz: 2112,
    name: 'CAFL 2112 Hz (histórico)',
    description: 'Valor heredado atribuido a listas CAFL junto con 993.98 Hz. No se afirma acción antiparasitaria.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['parasitos', 'rife', 'CAFL'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-993',
    hz: 993.98,
    name: 'CAFL 993.98 Hz (histórico)',
    description: 'Valor heredado atribuido a listas CAFL junto con 2112 Hz. No se afirma acción antiparasitaria.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['parasitos', 'rife', 'CAFL'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-5000',
    hz: 5000,
    name: 'Rife 5000 Hz (histórico)',
    description: 'Valor heredado atribuido a listas Rife sobre alergias o congestión. No representa tratamiento.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['alergias', 'senos', 'nasal', 'rife'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-10000',
    hz: 10000,
    name: 'Rife 10000 Hz (histórico)',
    description: 'Valor heredado atribuido a listas Rife sobre alergias. No representa tratamiento.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['alergias', 'rife'],
    source: 'Rife/CAFL',
  },
  {
    id: 'rife-20000',
    hz: 20000,
    name: 'Rife 20000 Hz (histórico)',
    description: 'Valor heredado atribuido a listas Rife y situado en el límite superior audible nominal. No se afirma uso terapéutico.',
    category: 'rife',
    domain: ['cuerpo'],
    evidence: 'especulativa',
    waveformRecommended: 'square',
    tags: ['general', 'terapeutico', 'rife'],
    source: 'Rife/CAFL',
  },

  // ─── NOGIER ───────────────────────────────────────────────────
  {
    id: 'nog-292',
    hz: 292,
    name: 'Nogier A',
    description: 'Valor heredado atribuido a clasificaciones Nogier sobre tejidos ectodérmicos. La asociación no está validada por este catálogo.',
    category: 'nogier',
    domain: ['cuerpo'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['nogier', 'piel', 'nervios', 'ectodermo'],
    source: 'Dr. Paul Nogier',
  },
  {
    id: 'nog-584',
    hz: 584,
    name: 'Nogier B',
    description: 'Valor heredado atribuido a clasificaciones Nogier sobre tejidos endodérmicos. La asociación no está validada por este catálogo.',
    category: 'nogier',
    domain: ['cuerpo'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['nogier', 'organos', 'endodermo'],
    source: 'Dr. Paul Nogier',
  },
  {
    id: 'nog-1168',
    hz: 1168,
    name: 'Nogier C',
    description: 'Valor heredado atribuido a clasificaciones Nogier sobre tejidos mesodérmicos. La asociación no está validada por este catálogo.',
    category: 'nogier',
    domain: ['cuerpo'],
    evidence: 'anecdotica',
    waveformRecommended: 'sine',
    tags: ['nogier', 'musculos', 'huesos', 'mesodermo'],
    source: 'Dr. Paul Nogier',
  },
];

// ─── Helpers ──────────────────────────────────────────────────────

export function getFrequencyById(id: string): FrequencyEntry | undefined {
  return FREQUENCY_DATABASE.find((f) => f.id === id);
}

export function getFrequenciesByCategory(category: FrequencyEntry['category']): FrequencyEntry[] {
  return FREQUENCY_DATABASE.filter((f) => f.category === category);
}

export function getFrequenciesByDomain(domain: FrequencyEntry['domain'][number]): FrequencyEntry[] {
  return FREQUENCY_DATABASE.filter((f) => f.domain.includes(domain));
}

export function searchFrequencies(query: string): FrequencyEntry[] {
  const q = query.toLowerCase();
  return FREQUENCY_DATABASE.filter(
    (f) =>
      f.name.toLowerCase().includes(q) ||
      f.description.toLowerCase().includes(q) ||
      f.tags.some((t) => t.includes(q)) ||
      f.hz.toString().includes(q)
  );
}

export const CATEGORY_INFO: Record<FrequencyEntry['category'], { label: string; color: string; icon: string }> = {
  brainwave: { label: 'Ondas Cerebrales', color: '#a78bfa', icon: '🧠' },
  solfeggio: { label: 'Solfeggio', color: '#fbbf24', icon: '🎵' },
  rife: { label: 'Rife / CAFL', color: '#f87171', icon: '⚡' },
  musical: { label: 'Musical', color: '#4ade80', icon: '🎶' },
  nogier: { label: 'Nogier', color: '#60a5fa', icon: '🔬' },
};

export const DOMAIN_INFO: Record<string, { label: string; color: string; icon: string }> = {
  cuerpo: { label: 'Cuerpo', color: '#f87171', icon: '🫀' },
  alma: { label: 'Alma', color: '#a78bfa', icon: '🧘' },
  espiritu: { label: 'Espíritu', color: '#67e8f9', icon: '✨' },
};

export const WAVEFORM_INFO: Record<string, { label: string; icon: string }> = {
  sine: { label: 'Sinusoidal', icon: '〰️' },
  square: { label: 'Cuadrada', icon: '⊓' },
  triangle: { label: 'Triangular', icon: '△' },
  sawtooth: { label: 'Sierra', icon: '⩘' },
};
